"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, HoldStats, PageResponse, permissionGranted, Project, UnitHold } from "@/lib/api";

const holdStatuses = ["PENDING_APPROVAL", "ACTIVE", "REJECTED", "RELEASED", "EXPIRED", "CONVERTED"];
const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Hold operation could not be completed";
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function UnitHoldsPage() {
  const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [result, setResult] = useState<PageResponse<UnitHold> | null>(null); const [stats, setStats] = useState<HoldStats | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  const [status, setStatus] = useState(""); const [holdType, setHoldType] = useState(""); const [projectId, setProjectId] = useState(""); const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const canApprove = permissionGranted(permissions, "inventory.approve"); const canRelease = permissionGranted(permissions, "inventory.assign");
  useEffect(() => { if (!session) return; let active = true; const params = new URLSearchParams({ page: String(page), page_size: "20" }); if (status) params.set("status", status); if (holdType) params.set("hold_type", holdType); if (projectId) params.set("project_id", projectId); void Promise.all([apiRequest<PageResponse<UnitHold>>(`/inventory/holds?${params}`), apiRequest<HoldStats>("/inventory/holds/stats"), apiRequest<PageResponse<Project>>("/projects?page_size=100")]).then(([holds, holdStats, projectData]) => { if (active) { setResult(holds); setStats(holdStats); setProjects(projectData.items); } }).catch((reason: unknown) => { if (active) setError(message(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [holdType, page, projectId, refresh, session, status]);
  async function decide(hold: UnitHold, decision: "APPROVED" | "REJECTED") { const notes = window.prompt(`${decision === "APPROVED" ? "Approval" : "Rejection"} notes`); if (!notes?.trim()) return; setSaving(true); setError(null); try { await apiRequest(`/inventory/holds/${hold.id}/approval`, { method: "POST", body: JSON.stringify({ status: decision, notes }) }); setNotice(`Hold ${decision.toLowerCase()}`); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function release(hold: UnitHold) { const reason = window.prompt("Release reason"); if (!reason?.trim()) return; setSaving(true); setError(null); try { await apiRequest(`/inventory/units/${hold.unit_id}/hold/release`, { method: "POST", body: JSON.stringify({ reason }) }); setNotice("Hold released and unit availability restored"); setRefresh((value) => value + 1); } catch (reasonValue) { setError(message(reasonValue)); } finally { setSaving(false); } }
  return <AppShell><main className="dashboard-content hold-content"><div className="management-heading"><div><p className="overline">Inventory control</p><h1>Unit holds</h1><p>Approval queue, live reservations, expiry visibility, and complete hold history.</p></div><Link className="button button-primary" href="/inventory">Open inventory</Link></div>
    {stats && <section className="hold-metrics"><article><span>Pending approval</span><strong>{stats.pending_approval}</strong></article><article><span>Active</span><strong>{stats.active}</strong></article><article><span>Expired</span><strong>{stats.expired}</strong></article><article><span>Released / rejected</span><strong>{stats.released + stats.rejected}</strong></article><article><span>Converted</span><strong>{stats.converted}</strong></article></section>}
    <section className="inventory-filter-panel hold-filters"><select value={status} onChange={(event) => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option>{holdStatuses.map((item) => <option key={item}>{item}</option>)}</select><select value={holdType} onChange={(event) => { setPage(1); setHoldType(event.target.value); }}><option value="">Soft & hard holds</option><option value="SOFT_HOLD">Soft hold</option><option value="HARD_HOLD">Hard hold</option></select><select value={projectId} onChange={(event) => { setPage(1); setProjectId(event.target.value); }}><option value="">All projects</option>{projects.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button type="button" onClick={() => { setStatus(""); setHoldType(""); setProjectId(""); setPage(1); }}>Clear filters</button></section>
    {error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}
    <section className="data-card"><div className="hold-table"><div className="hold-row head"><span>Unit</span><span>Customer</span><span>Salesperson</span><span>Reason</span><span>Timeline</span><span>Status</span><span /></div>{loading ? <div className="center-inline"><span className="spinner"/>Loading holds...</div> : result?.items.length ? result.items.map((hold) => <div className="hold-row" key={hold.id}><span><strong>{hold.unit_number}</strong><small>{hold.project_name} · {hold.hold_type?.replaceAll("_", " ") ?? "Legacy hold"}</small></span><span><strong>{hold.customer_name ?? "Legacy record"}</strong><small>{hold.customer_id ?? "No customer reference"}</small></span><span><strong>{hold.salesperson_name}</strong><small>{hold.approver_name ? `Approver: ${hold.approver_name}` : "Awaiting approver"}</small></span><span><p>{hold.hold_reason ?? "No reason recorded"}</p>{hold.approval_notes && <small>Decision: {hold.approval_notes}</small>}</span><span><strong>Expires {dateTime(hold.expires_at)}</strong><small>Started {dateTime(hold.starts_at)}</small></span><span><em className={`hold-status status-${hold.status.toLowerCase()}`}>{hold.status.replaceAll("_", " ")}</em></span><span className="hold-actions">{hold.status === "PENDING_APPROVAL" && canApprove && <><button disabled={saving} className="approve" onClick={() => void decide(hold, "APPROVED")}>Approve</button><button disabled={saving} className="reject" onClick={() => void decide(hold, "REJECTED")}>Reject</button></>}{["PENDING_APPROVAL", "ACTIVE"].includes(hold.status) && canRelease && <button disabled={saving} onClick={() => void release(hold)}>Release</button>}</span></div>) : <div className="empty-state"><strong>No hold records found</strong><p>No default holds are created. New requests appear from live inventory actions.</p></div>}</div>{result && result.pages > 1 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page} of {result.pages}</span><button disabled={page === result.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div>}</section>
  </main></AppShell>;
}
