"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { QuotationNavigation } from "@/components/quotation-navigation";
import { apiRequest, ApiError, ApprovalMatrixOptions, PageResponse, permissionGranted, PriceList, Project, RecordStatus } from "@/lib/api";

type Draft = { project_id: string; name: string; code: string; currency: string; effective_from: string; effective_to: string; base_rate: string; floor_start: string; floor_amount: string; floor_sqft_rate: string; self_limit: string; maximum_discount: string; booking_kind: "" | "fixed" | "percentage"; booking_value: string; premiums: string; parking: string; amenities: string; charges: string; taxes: string; overrides: string; approval_matrix: string };
const empty: Draft = { project_id: "", name: "", code: "", currency: "INR", effective_from: "", effective_to: "", base_rate: "", floor_start: "", floor_amount: "", floor_sqft_rate: "", self_limit: "0", maximum_discount: "", booking_kind: "", booking_value: "", premiums: "[]", parking: "[]", amenities: "[]", charges: "[]", taxes: "[]", overrides: "{}", approval_matrix: "[]" };
const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Price list operation failed";
const parse = (value: string, label: string) => { try { return JSON.parse(value); } catch { throw new Error(`${label} must contain valid JSON`); } };

export default function PriceListsPage() {
  const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [result, setResult] = useState<PageResponse<PriceList> | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  const [approvalOptions, setApprovalOptions] = useState<ApprovalMatrixOptions>({ users: [], roles: [] });
  const [projectId, setProjectId] = useState(""); const [status, setStatus] = useState(""); const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false); const [draft, setDraft] = useState<Draft>(empty); const [saving, setSaving] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [refresh, setRefresh] = useState(0);
  const canCreate = permissionGranted(permissions, "quotations.create"); const canUpdate = permissionGranted(permissions, "quotations.update"); const canApprove = permissionGranted(permissions, "quotations.approve"); const canDelete = permissionGranted(permissions, "quotations.delete");
  useEffect(() => { if (!session) return; let active = true; const params = new URLSearchParams({ page_size: "100" }); if (query) params.set("q", query); if (projectId) params.set("project_id", projectId); if (status) params.set("status", status); void Promise.all([apiRequest<PageResponse<PriceList>>(`/price-lists?${params}`), apiRequest<PageResponse<Project>>("/projects?page_size=100"), apiRequest<ApprovalMatrixOptions>("/discount-approval-options")]).then(([lists, projectData, options]) => { if (active) { setResult(lists); setProjects(projectData.items); setApprovalOptions(options); } }).catch((reason: unknown) => { if (active) setError(message(reason)); }); return () => { active = false; }; }, [projectId, query, refresh, session, status]);

  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try {
    const rules = {
      base_rate_per_sqft: draft.base_rate || null,
      unit_overrides: parse(draft.overrides, "Unit overrides"),
      floor_rise: draft.floor_start && (draft.floor_amount || draft.floor_sqft_rate) ? { label: "Floor rise", start_floor: Number(draft.floor_start), amount_per_floor: draft.floor_amount || null, rate_per_sqft_per_floor: draft.floor_sqft_rate || null, taxable: true } : null,
      premiums: parse(draft.premiums, "Premiums"), parking_options: parse(draft.parking, "Parking options"), amenity_charges: parse(draft.amenities, "Amenities"), charges: parse(draft.charges, "Charges"), taxes: parse(draft.taxes, "Taxes"),
      discount_policy: { self_approval_limit_percent: draft.self_limit || "0", maximum_discount_percent: draft.maximum_discount || null, approval_matrix: parse(draft.approval_matrix, "Approval matrix") },
      booking_amount: draft.booking_kind && draft.booking_value ? { calculation: draft.booking_kind, value: draft.booking_value } : null
    };
    const body = editingId ? { name: draft.name, effective_from: draft.effective_from, effective_to: draft.effective_to || null, pricing_rules: rules } : { project_id: draft.project_id, name: draft.name, code: draft.code, currency: draft.currency, effective_from: draft.effective_from, effective_to: draft.effective_to || null, pricing_rules: rules };
    await apiRequest(editingId ? `/price-lists/${editingId}` : "/price-lists", { method: editingId ? "PATCH" : "POST", body: JSON.stringify(body) });
    setDraft(empty); setEditingId(null); setOpen(false); setNotice(editingId ? "Draft price list updated" : "Price list created as draft"); setRefresh((value) => value + 1);
  } catch (reason) { setError(reason instanceof Error ? reason.message : message(reason)); } finally { setSaving(false); } }
  async function setRecordStatus(item: PriceList, next: RecordStatus) { try { await apiRequest(`/price-lists/${item.id}/status`, { method: "POST", body: JSON.stringify({ status: next }) }); setNotice(`${item.name} is now ${next.toLowerCase()}`); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } }
  async function remove(item: PriceList) { if (!confirm(`Delete draft price list ${item.name}?`)) return; try { await apiRequest(`/price-lists/${item.id}`, { method: "DELETE" }); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } }
  function edit(item: PriceList) { const rules = item.pricing_rules; setEditingId(item.id); setDraft({ project_id: item.project_id, name: item.name, code: item.code, currency: item.currency, effective_from: item.effective_from, effective_to: item.effective_to ?? "", base_rate: rules.base_rate_per_sqft ?? "", floor_start: rules.floor_rise ? String(rules.floor_rise.start_floor) : "", floor_amount: rules.floor_rise?.amount_per_floor ?? "", floor_sqft_rate: rules.floor_rise?.rate_per_sqft_per_floor ?? "", self_limit: rules.discount_policy.self_approval_limit_percent, maximum_discount: rules.discount_policy.maximum_discount_percent ?? "", booking_kind: rules.booking_amount?.calculation ?? "", booking_value: rules.booking_amount?.value ?? "", premiums: JSON.stringify(rules.premiums, null, 2), parking: JSON.stringify(rules.parking_options, null, 2), amenities: JSON.stringify(rules.amenity_charges, null, 2), charges: JSON.stringify(rules.charges, null, 2), taxes: JSON.stringify(rules.taxes, null, 2), overrides: JSON.stringify(rules.unit_overrides, null, 2), approval_matrix: JSON.stringify(rules.discount_policy.approval_matrix ?? [], null, 2) }); setOpen(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  const set = (key: keyof Draft, value: string) => setDraft((current) => ({ ...current, [key]: value }));
  return <AppShell><main className="dashboard-content quote-content"><div className="management-heading"><div><p className="overline">Pricing control</p><h1>Price lists</h1><p>Every commercial amount comes from a versioned project configuration or its unit record.</p></div>{canCreate && <button className="button button-primary" onClick={() => { setEditingId(null); setDraft(empty); setOpen((value) => !value); }}>{open ? "Close editor" : "Create price list"}</button>}</div><QuotationNavigation />
    {error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}
    {open && <form className="panel pricing-editor" onSubmit={create}><div className="panel-heading"><div><h2>{editingId ? "Edit draft pricing configuration" : "New pricing configuration"}</h2><p>Save as draft, validate it with a cost-sheet preview, then activate it.</p></div></div><div className="lead-form-grid">
      <label className="field"><span>Project</span><select required value={draft.project_id} onChange={(e) => set("project_id", e.target.value)}><option value="">Select project</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Name</span><input required minLength={2} value={draft.name} onChange={(e) => set("name", e.target.value)}/></label><label className="field"><span>Code</span><input required pattern="[A-Z0-9][A-Z0-9_-]*" value={draft.code} onChange={(e) => set("code", e.target.value.toUpperCase())}/></label><label className="field"><span>Currency</span><input required minLength={3} maxLength={3} value={draft.currency} onChange={(e) => set("currency", e.target.value.toUpperCase())}/></label><label className="field"><span>Effective from</span><input required type="date" value={draft.effective_from} onChange={(e) => set("effective_from", e.target.value)}/></label><label className="field"><span>Effective to</span><input type="date" min={draft.effective_from} value={draft.effective_to} onChange={(e) => set("effective_to", e.target.value)}/></label>
    </div><h3>Base, floor rise & controls</h3><div className="pricing-inputs"><label className="field"><span>Base rate / sq ft</span><input type="number" min="0" step="0.01" value={draft.base_rate} onChange={(e) => set("base_rate", e.target.value)} placeholder="Falls back to unit base price"/></label><label className="field"><span>Floor rise starts at</span><input type="number" value={draft.floor_start} onChange={(e) => set("floor_start", e.target.value)}/></label><label className="field"><span>Amount / floor</span><input type="number" min="0" step="0.01" value={draft.floor_amount} disabled={Boolean(draft.floor_sqft_rate)} onChange={(e) => set("floor_amount", e.target.value)}/></label><label className="field"><span>Rate / sq ft / floor</span><input type="number" min="0" step="0.01" value={draft.floor_sqft_rate} disabled={Boolean(draft.floor_amount)} onChange={(e) => set("floor_sqft_rate", e.target.value)}/></label><label className="field"><span>Self-approval limit %</span><input required type="number" min="0" max="100" step="0.01" value={draft.self_limit} onChange={(e) => set("self_limit", e.target.value)}/></label><label className="field"><span>Maximum discount %</span><input type="number" min="0" max="100" step="0.01" value={draft.maximum_discount} onChange={(e) => set("maximum_discount", e.target.value)}/></label><label className="field"><span>Booking calculation</span><select value={draft.booking_kind} onChange={(e) => set("booking_kind", e.target.value)}><option value="">Manual at cost sheet</option><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></label><label className="field"><span>Booking value</span><input type="number" min="0" step="0.01" value={draft.booking_value} disabled={!draft.booking_kind} onChange={(e) => set("booking_value", e.target.value)}/></label></div>
    <section className="approval-matrix-editor"><div><h3>Discount approval matrix</h3><p>Discounts above the self-approval limit must match a level and can only be decided by its configured users or roles.</p><div className="approver-reference"><span><strong>Roles</strong>{approvalOptions.roles.map((item) => <small key={item.id}>{item.name}: {item.id}</small>)}</span><span><strong>Users</strong>{approvalOptions.users.map((item) => <small key={item.id}>{item.name}: {item.id}</small>)}</span></div></div><label className="field"><span>Approval levels (JSON)</span><textarea rows={8} spellCheck={false} value={draft.approval_matrix} onChange={(e) => set("approval_matrix", e.target.value)} placeholder='[{"name":"Level 1","minimum_discount_percent":2,"maximum_discount_percent":5,"approver_role_ids":["role-id"],"approver_user_ids":[]}]'/><small>Levels cannot overlap. Each level needs at least one active approver user or role.</small></label></section>
    <details className="pricing-advanced"><summary>Advanced components and unit overrides</summary><p>JSON arrays use code, label, calculation, value, taxable and optional. Matching can target unit type, facing, tower or floor.</p><div className="pricing-json-grid">{([["premiums", "Premium rules"], ["parking", "Parking options"], ["amenities", "Amenity charges"], ["charges", "Other charges"], ["taxes", "Tax rules"], ["overrides", "Unit overrides"]] as Array<[keyof Draft, string]>).map(([key, label]) => <label className="field" key={key}><span>{label}</span><textarea rows={5} spellCheck={false} value={draft[key]} onChange={(e) => set(key, e.target.value)}/></label>)}</div></details><div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button disabled={saving} className="button button-primary">{saving ? "Saving..." : "Save draft price list"}</button></div></form>}
    <section className="inventory-filter-panel price-list-filters"><input placeholder="Search name or code" value={query} onChange={(e) => setQuery(e.target.value)}/><select value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">All projects</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></section>
    {canUpdate && result?.items.some((item) => item.status === "DRAFT") && <div className="draft-edit-strip"><strong>Draft configurations</strong>{result.items.filter((item) => item.status === "DRAFT").map((item) => <span key={item.id}><button type="button" onClick={() => edit(item)}>Edit {item.name}</button>{canDelete && item.cost_sheet_count === 0 && <button type="button" className="danger-link" onClick={() => void remove(item)}>Delete</button>}</span>)}</div>}
    <section className="price-list-grid">{result?.items.length ? result.items.map((item) => <article className="panel price-list-card" key={item.id}><header><span className={`quote-status status-${item.status.toLowerCase()}`}>{item.status}</span><small>{item.code} · v{item.version}</small></header><h2>{item.name}</h2><p>{item.project_name}</p><dl><div><dt>Effective</dt><dd>{new Date(item.effective_from).toLocaleDateString("en-IN")} — {item.effective_to ? new Date(item.effective_to).toLocaleDateString("en-IN") : "Open ended"}</dd></div><div><dt>Base pricing</dt><dd>{item.pricing_rules.base_rate_per_sqft ? `${item.currency} ${item.pricing_rules.base_rate_per_sqft} / sq ft` : "Unit-level base price"}</dd></div><div><dt>Cost sheets</dt><dd>{item.cost_sheet_count}</dd></div></dl><footer>{canApprove && item.status !== "ACTIVE" && item.status !== "ARCHIVED" && <button onClick={() => void setRecordStatus(item, "ACTIVE")}>Activate</button>}{canApprove && item.status === "ACTIVE" && <button onClick={() => void setRecordStatus(item, "INACTIVE")}>Deactivate</button>}{canUpdate && item.status !== "ARCHIVED" && <button onClick={() => void setRecordStatus(item, "ARCHIVED")}>Archive</button>}{canDelete && item.status === "INACTIVE" && item.cost_sheet_count === 0 && <button className="danger-link" onClick={() => void remove(item)}>Delete</button>}</footer></article>) : <div className="empty-state panel"><strong>No price lists yet</strong><p>Create your first project-specific configuration. Nothing is pre-populated.</p></div>}</section>
  </main></AppShell>;
}
