"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, PageResponse, permissionGranted, Project, SiteVisit, SiteVisitStats, VisitStatus } from "@/lib/api";

const statuses: VisitStatus[] = ["SCHEDULED", "CONFIRMED", "CHECKED_IN", "COMPLETED", "CANCELLED", "NO_SHOW"];
function errorMessage(reason: unknown) { return reason instanceof ApiError ? reason.message : "Site visits are unavailable"; }
function dateTime(value: string) { return new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }); }

export default function SiteVisitsPage() {
  const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [result, setResult] = useState<PageResponse<SiteVisit> | null>(null); const [stats, setStats] = useState<SiteVisitStats | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  const [queryInput, setQueryInput] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [projectId, setProjectId] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const canCreate = permissionGranted(permissions, "visits.create");

  useEffect(() => { if (!session) return; let active = true; const params = new URLSearchParams({ page: String(page), page_size: "20" }); if (query) params.set("q", query); if (status) params.set("status", status); if (projectId) params.set("project_id", projectId); if (dateFrom) params.set("date_from", new Date(`${dateFrom}T00:00:00`).toISOString()); if (dateTo) params.set("date_to", new Date(`${dateTo}T23:59:59`).toISOString()); void apiRequest<PageResponse<SiteVisit>>(`/site-visits?${params}`).then((data) => { if (active) setResult(data); }).catch((reason: unknown) => { if (active) setError(errorMessage(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [dateFrom, dateTo, page, projectId, query, session, status]);
  useEffect(() => { if (!session) return; let active = true; void Promise.all([apiRequest<SiteVisitStats>("/site-visits/stats"), apiRequest<PageResponse<Project>>("/projects?page_size=100")]).then(([visitStats, projectPage]) => { if (!active) return; setStats(visitStats); setProjects(projectPage.items); }).catch((reason: unknown) => { if (active) setError(errorMessage(reason)); }); return () => { active = false; }; }, [session]);

  function search(event: FormEvent) { event.preventDefault(); setPage(1); setQuery(queryInput.trim()); }
  function clear() { setQueryInput(""); setQuery(""); setStatus(""); setProjectId(""); setDateFrom(""); setDateTo(""); setPage(1); }

  return <AppShell><main className="dashboard-content visit-content"><div className="management-heading"><div><p className="overline">Field sales operations</p><h1>Site visits</h1><p>Schedule, assign, check in, capture feedback, and keep every visit connected to its sales journey.</p></div><div className="heading-actions"><Link className="button button-secondary" href="/calendar">Calendar</Link>{canCreate && <Link className="button button-primary" href="/site-visits/create">Schedule visit</Link>}</div></div>
    {stats && <section className="visit-metrics"><article><span>Total visits</span><strong>{stats.total}</strong></article><article><span>Upcoming</span><strong>{stats.upcoming}</strong></article><article><span>Today</span><strong>{stats.today}</strong></article><article><span>Checked in</span><strong>{stats.checked_in}</strong></article><article><span>Completed</span><strong>{stats.completed}</strong></article></section>}
    <section className="visit-filters"><form onSubmit={search}><input value={queryInput} onChange={(e) => setQueryInput(e.target.value)} placeholder="Search lead, customer, project, or outcome..." /><button className="button button-primary">Search</button></form><div><select value={status} onChange={(e) => { setPage(1); setStatus(e.target.value); }}><option value="">All statuses</option>{statuses.map((item) => <option value={item} key={item}>{item.replaceAll("_", " ")}</option>)}</select><select value={projectId} onChange={(e) => { setPage(1); setProjectId(e.target.value); }}><option value="">All projects</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label><span>From</span><input type="date" value={dateFrom} onChange={(e) => { setPage(1); setDateFrom(e.target.value); }} /></label><label><span>To</span><input type="date" value={dateTo} onChange={(e) => { setPage(1); setDateTo(e.target.value); }} /></label><button type="button" onClick={clear}>Clear</button></div></section>
    {error && <div className="alert alert-error page-alert">{error}</div>}
    <section className="data-card visit-table-card"><div className="visit-table"><div className="visit-row head"><span>Contact</span><span>Project & units</span><span>Schedule</span><span>Salesperson</span><span>Status</span><span /></div>{loading ? <div className="center-inline"><span className="spinner" />Loading visits...</div> : result?.items.length ? result.items.map((visit) => <div className="visit-row" key={visit.id}><span><strong>{visit.customer_name ?? visit.lead_name}</strong><small>{visit.customer_name && visit.lead_name ? `Lead · ${visit.lead_name}` : visit.customer_name ? "Customer" : "Lead"}</small></span><span><strong>{visit.project_name}</strong><small>{visit.interested_units.map((unit) => unit.unit_number).join(", ") || "No specific units"}</small></span><span><strong>{dateTime(visit.scheduled_at)}</strong><small>{visit.attendees.length} attendee{visit.attendees.length === 1 ? "" : "s"}</small></span><span>{visit.assigned_user_name ?? "Unassigned"}</span><span><em className={`visit-status status-${visit.status.toLowerCase()}`}>{visit.status.replaceAll("_", " ")}</em></span><span><Link href={`/site-visits/${visit.id}`}>Open →</Link></span></div>) : <div className="customer-empty"><span>+</span><strong>No site visits found</strong><p>Schedule a real visit when a lead or customer is ready.</p></div>}</div><div className="pagination"><button disabled={!result || page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {result?.page ?? 1} of {Math.max(result?.pages ?? 0, 1)}</span><button disabled={!result || page >= result.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div></section>
  </main></AppShell>;
}
