"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, PageResponse, PartnerOptions, PartnerStats, PartnerSummary, permissionGranted } from "@/lib/api";

const money = (value: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value));

export default function PartnersPage() {
  const { session } = useAuth(); const canCreate = permissionGranted(session?.user.permissions ?? [], "partners.create");
  const [result, setResult] = useState<PageResponse<PartnerSummary> | null>(null); const [stats, setStats] = useState<PartnerStats | null>(null); const [options, setOptions] = useState<PartnerOptions>({ managers: [], territories: [], projects: [] });
  const [queryInput, setQueryInput] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [territory, setTerritory] = useState(""); const [project, setProject] = useState(""); const [page, setPage] = useState(1); const [modal, setModal] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const params = new URLSearchParams({ page: String(page), page_size: "20" }); if (query) params.set("q", query); if (status) params.set("status", status); if (territory) params.set("territory_id", territory); if (project) params.set("project_id", project); try { const [rows, totals, choices] = await Promise.all([apiRequest<PageResponse<PartnerSummary>>(`/partners?${params}`), apiRequest<PartnerStats>("/partners/stats"), apiRequest<PartnerOptions>("/partners/options")]); setResult(rows); setStats(totals); setOptions(choices); setError(null); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Channel partners could not be loaded"); } }, [page, project, query, status, territory]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, [load]);
  function search(event: FormEvent) { event.preventDefault(); setPage(1); setQuery(queryInput.trim()); }
  return <AppShell><main className="dashboard-content partner-content"><div className="management-heading"><div><p className="overline">Channel ecosystem</p><h1>Channel partners</h1><p>Application-to-activation governance, protected lead attribution, commissions, payouts, and disputes.</p></div>{canCreate && <button className="button button-primary" onClick={() => setModal(true)}>New application</button>}</div>{error && <div className="alert alert-error">{error}</div>}
    {stats && <section className="partner-metrics"><article><span>Total partners</span><strong>{stats.total}</strong></article><article><span>Applications</span><strong>{stats.applications}</strong></article><article><span>Verification</span><strong>{stats.verification}</strong></article><article><span>Approval queue</span><strong>{stats.approval_queue}</strong></article><article><span>Active</span><strong>{stats.active}</strong></article><article><span>Payable</span><strong>{money(stats.payable_commission)}</strong></article></section>}
    <section className="inventory-filter-panel partner-filters"><form className="inventory-search" onSubmit={search}><input value={queryInput} onChange={(event) => setQueryInput(event.target.value)} placeholder="Search company, code, registration, email..."/><button className="button button-primary">Search</button></form><div><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All lifecycle stages</option>{["APPLICATION","DOCUMENT_VERIFICATION","AGREEMENT_PENDING","APPROVAL_PENDING","APPROVED","ACTIVE","REJECTED","SUSPENDED","INACTIVE"].map((item) => <option key={item}>{item}</option>)}</select><select value={territory} onChange={(event) => { setTerritory(event.target.value); setPage(1); }}><option value="">All territories</option>{options.territories.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select><select value={project} onChange={(event) => { setProject(event.target.value); setPage(1); }}><option value="">All projects</option>{options.projects.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></div></section>
    <section className="data-card partner-table-card"><div className="partner-table"><div className="partner-row head"><span>Partner</span><span>Primary contact</span><span>Lifecycle</span><span>Performance</span><span>Commission</span><span/></div>{result?.items.length ? result.items.map((item) => <Link className="partner-row" href={`/partners/${item.id}`} key={item.id}><span><strong>{item.name}</strong><small>{item.code} · {item.partner_type ?? "Channel partner"}</small></span><span><strong>{item.contact_name ?? "Not assigned"}</strong><small>{item.email ?? item.phone ?? "No contact"}</small></span><span><em className={`post-sales-status status-${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</em><small>{item.manager_name ?? "No manager"}</small></span><span><strong>{item.active_leads} protected leads</strong><small>{item.confirmed_bookings} confirmed bookings</small></span><span><strong>{money(item.payable_commission)}</strong><small>Eligible / approved</small></span><span>View →</span></Link>) : <div className="customer-empty"><span>CP</span><strong>No channel partners</strong><p>Partner profiles appear only after a real application is submitted.</p></div>}</div><div className="pagination"><button disabled={!result || page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {result?.page ?? 1} of {Math.max(result?.pages ?? 0, 1)}</span><button disabled={!result || page >= result.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div></section>
    {modal && <ApplicationModal options={options} onClose={() => setModal(false)} onCreated={() => { setModal(false); void load(); }} onError={setError}/>}</main></AppShell>;
}

function ApplicationModal({ options, onClose, onCreated, onError }: { options: PartnerOptions; onClose: () => void; onCreated: () => void; onError: (value: string) => void }) {
  const [saving, setSaving] = useState(false); const [form, setForm] = useState({ code: "", name: "", legal_name: "", partner_type: "COMPANY", registration_number: "", contact_name: "", email: "", phone: "", address_line1: "", city: "", state: "", postal_code: "", country: "India", manager_user_id: "", application_notes: "" });
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value })) });
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiRequest("/partners", { method: "POST", body: JSON.stringify({ ...form, manager_user_id: form.manager_user_id || null }) }); onCreated(); } catch (reason) { onError(reason instanceof ApiError ? reason.message : "Application could not be submitted"); } finally { setSaving(false); } }
  return <div className="modal-backdrop"><form className="modal-card partner-application-modal" onSubmit={submit}><div className="modal-heading"><div><p className="overline">Application</p><h2>Register channel partner</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><div className="post-sales-modal-body partner-form-grid"><label className="field"><span>Partner code</span><input required pattern="[A-Za-z0-9][A-Za-z0-9_-]*" {...field("code")}/></label><label className="field"><span>Partner type</span><select {...field("partner_type")}><option>COMPANY</option><option>INDIVIDUAL_BROKER</option><option>AGENCY</option></select></label><label className="field"><span>Trading name</span><input required minLength={2} {...field("name")}/></label><label className="field"><span>Legal name</span><input required minLength={2} {...field("legal_name")}/></label><label className="field"><span>Registration number</span><input required {...field("registration_number")}/></label><label className="field"><span>Channel manager</span><select {...field("manager_user_id")}><option value="">Assign later</option>{options.managers.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="field"><span>Primary contact</span><input required {...field("contact_name")}/></label><label className="field"><span>Email</span><input required type="email" {...field("email")}/></label><label className="field"><span>Phone</span><input required {...field("phone")}/></label><label className="field"><span>Registered address</span><input required {...field("address_line1")}/></label><label className="field"><span>City</span><input required {...field("city")}/></label><label className="field"><span>State</span><input required {...field("state")}/></label><label className="field"><span>Postal code</span><input required {...field("postal_code")}/></label><label className="field"><span>Country</span><input required {...field("country")}/></label><label className="field span-two"><span>Application notes</span><textarea rows={3} {...field("application_notes")}/></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button disabled={saving} className="button button-primary">Submit application</button></div></form></div>;
}
