"""Compatibility export surface for the domain-oriented SQLAlchemy models."""

from app.models.crm import (
    Customer,
    CustomerDocument,
    Lead,
    LeadActivity,
    LeadAssignment,
    LeadSource,
)
from app.models.enums import BookingStatus, LeadStatus, UnitStatus
from app.models.inventory import Floor, PriceList, Project, Tower, Unit, UnitHold
from app.models.operations import AuditLog, Maintenance, Notification, ServiceRequest
from app.models.organization import (
    Branch,
    Department,
    Organization,
    PasswordResetToken,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    User,
    UserRole,
)
from app.models.partners import ChannelPartner, Commission, CommissionPayout, PartnerLead
from app.models.post_sales import ConstructionUpdate, Handover, Possession
from app.models.rentals import Lease, RentalInvoice, RentPayment, Tenant
from app.models.revenue import (
    Agreement,
    Cancellation,
    CustomerLedger,
    DemandLetter,
    Installment,
    Payment,
    PaymentPlan,
    Receipt,
    Refund,
    UnitTransfer,
)
from app.models.sales import (
    Booking,
    BookingApproval,
    BookingDocument,
    Quotation,
    QuotationItem,
    SiteVisit,
)

__all__ = [
    "Agreement",
    "AuditLog",
    "Booking",
    "BookingApproval",
    "BookingDocument",
    "BookingStatus",
    "Branch",
    "Cancellation",
    "ChannelPartner",
    "Commission",
    "CommissionPayout",
    "ConstructionUpdate",
    "Customer",
    "CustomerDocument",
    "CustomerLedger",
    "DemandLetter",
    "Department",
    "Floor",
    "Handover",
    "Installment",
    "Lead",
    "LeadActivity",
    "LeadAssignment",
    "LeadSource",
    "LeadStatus",
    "Lease",
    "Maintenance",
    "Notification",
    "Organization",
    "PasswordResetToken",
    "PartnerLead",
    "Payment",
    "PaymentPlan",
    "Permission",
    "Possession",
    "PriceList",
    "Project",
    "Quotation",
    "QuotationItem",
    "Receipt",
    "RefreshToken",
    "Refund",
    "RentalInvoice",
    "RentPayment",
    "Role",
    "RolePermission",
    "ServiceRequest",
    "SiteVisit",
    "Tenant",
    "Tower",
    "Unit",
    "UnitHold",
    "UnitStatus",
    "UnitTransfer",
    "User",
    "UserRole",
]
