from enum import StrEnum


class LeadStatus(StrEnum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    ATTEMPTED = "ATTEMPTED"
    CONTACTED = "CONTACTED"
    QUALIFIED = "QUALIFIED"
    DISQUALIFIED = "DISQUALIFIED"
    LOST = "LOST"
    CONVERTED = "CONVERTED"


class CustomerStatus(StrEnum):
    PROSPECT = "PROSPECT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BLOCKED = "BLOCKED"


class RecordStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ARCHIVED = "ARCHIVED"


class DocumentStatus(StrEnum):
    PENDING = "PENDING"
    UPLOADED = "UPLOADED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ActivityType(StrEnum):
    CALL = "CALL"
    EMAIL = "EMAIL"
    MEETING = "MEETING"
    NOTE = "NOTE"
    STATUS_CHANGE = "STATUS_CHANGE"
    FOLLOW_UP = "FOLLOW_UP"


class ProjectStatus(StrEnum):
    PLANNING = "PLANNING"
    LAUNCHED = "LAUNCHED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    COMPLETED = "COMPLETED"
    ON_HOLD = "ON_HOLD"
    ARCHIVED = "ARCHIVED"


class UnitStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    SOFT_HOLD = "SOFT_HOLD"
    HARD_HOLD = "HARD_HOLD"
    BOOKING_INITIATED = "BOOKING_INITIATED"
    BOOKED = "BOOKED"
    SOLD = "SOLD"
    CANCELLED_RELEASED = "CANCELLED_RELEASED"


class HoldStatus(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"
    CONVERTED = "CONVERTED"


class HoldType(StrEnum):
    SOFT_HOLD = "SOFT_HOLD"
    HARD_HOLD = "HARD_HOLD"


class VisitStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    CONFIRMED = "CONFIRMED"
    CHECKED_IN = "CHECKED_IN"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class QuotationStatus(StrEnum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class CostSheetStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED = "CONVERTED"
    VOIDED = "VOIDED"


class BookingStatus(StrEnum):
    DRAFT = "DRAFT"
    DOCUMENTATION_PENDING = "DOCUMENTATION_PENDING"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    SUBMITTED = "SUBMITTED"
    VERIFICATION = "VERIFICATION"
    APPROVAL = "APPROVAL"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class FinancingStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    APPLIED = "APPLIED"
    UNDER_REVIEW = "UNDER_REVIEW"
    SANCTIONED = "SANCTIONED"
    REJECTED = "REJECTED"
    DISBURSED = "DISBURSED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class AgreementStatus(StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    SIGNED = "SIGNED"
    REGISTERED = "REGISTERED"
    TERMINATED = "TERMINATED"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    VOIDED = "VOIDED"
    REFUNDED = "REFUNDED"


class InstallmentStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    DUE = "DUE"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    WAIVED = "WAIVED"


class LedgerEntryType(StrEnum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"
    ADJUSTMENT = "ADJUSTMENT"


class ReconciliationStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    MISMATCHED = "MISMATCHED"
    RESOLVED = "RESOLVED"


class FinancialChargeType(StrEnum):
    PENALTY = "PENALTY"
    INTEREST = "INTEREST"


class FinancialChargeStatus(StrEnum):
    APPLIED = "APPLIED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    WAIVED = "WAIVED"


class WorkflowStatus(StrEnum):
    REQUESTED = "REQUESTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class PartnerStatus(StrEnum):
    PENDING = "PENDING"
    APPLICATION = "APPLICATION"
    DOCUMENT_VERIFICATION = "DOCUMENT_VERIFICATION"
    AGREEMENT_PENDING = "AGREEMENT_PENDING"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class CommissionStatus(StrEnum):
    PENDING = "PENDING"
    ELIGIBLE = "ELIGIBLE"
    APPROVED = "APPROVED"
    PAID = "PAID"
    REVERSED = "REVERSED"


class ProgressStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class PossessionStatus(StrEnum):
    PENDING = "PENDING"
    OFFERED = "OFFERED"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"


class PostBookingStage(StrEnum):
    AGREEMENT_PENDING = "AGREEMENT_PENDING"
    CONSTRUCTION = "CONSTRUCTION"
    POSSESSION_READINESS = "POSSESSION_READINESS"
    FINAL_DEMAND = "FINAL_DEMAND"
    FINAL_PAYMENT = "FINAL_PAYMENT"
    NO_DUES = "NO_DUES"
    SNAGGING = "SNAGGING"
    POSSESSION = "POSSESSION"
    HANDOVER = "HANDOVER"
    COMPLETED = "COMPLETED"


class SnagStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    ACCEPTED = "ACCEPTED"
    WAIVED = "WAIVED"


class TenantStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BLACKLISTED = "BLACKLISTED"


class RentalPropertyStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    OCCUPIED = "OCCUPIED"
    MAINTENANCE = "MAINTENANCE"
    INACTIVE = "INACTIVE"


class RentScheduleStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    INVOICED = "INVOICED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    WAIVED = "WAIVED"


class LeaseStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_SIGNATURE = "PENDING_SIGNATURE"
    SIGNED = "SIGNED"
    MOVE_IN_PENDING = "MOVE_IN_PENDING"
    ACTIVE = "ACTIVE"
    NOTICE_GIVEN = "NOTICE_GIVEN"
    MOVE_OUT_PENDING = "MOVE_OUT_PENDING"
    EXPIRED = "EXPIRED"
    TERMINATED = "TERMINATED"
    RENEWED = "RENEWED"


class InvoiceStatus(StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    VOIDED = "VOIDED"


class ServicePriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class ServiceStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class TicketStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class EscalationStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"


class NotificationStatus(StrEnum):
    QUEUED = "QUEUED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    READ = "READ"


class NotificationEventType(StrEnum):
    LEAD_ASSIGNED = "LEAD_ASSIGNED"
    FOLLOW_UP_REMINDER = "FOLLOW_UP_REMINDER"
    SITE_VISIT_SCHEDULED = "SITE_VISIT_SCHEDULED"
    SITE_VISIT_UPDATED = "SITE_VISIT_UPDATED"
    QUOTATION_CREATED = "QUOTATION_CREATED"
    QUOTATION_STATUS_CHANGED = "QUOTATION_STATUS_CHANGED"
    DISCOUNT_APPROVAL_REQUESTED = "DISCOUNT_APPROVAL_REQUESTED"
    DISCOUNT_APPROVAL_DECIDED = "DISCOUNT_APPROVAL_DECIDED"
    UNIT_HOLD_EXPIRING = "UNIT_HOLD_EXPIRING"
    UNIT_HOLD_EXPIRED = "UNIT_HOLD_EXPIRED"
    BOOKING_CREATED = "BOOKING_CREATED"
    BOOKING_STATUS_CHANGED = "BOOKING_STATUS_CHANGED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    INSTALLMENT_DUE = "INSTALLMENT_DUE"
    INSTALLMENT_OVERDUE = "INSTALLMENT_OVERDUE"
    DEMAND_LETTER_ISSUED = "DEMAND_LETTER_ISSUED"
    POSSESSION_UPDATED = "POSSESSION_UPDATED"
    SERVICE_REQUEST_CREATED = "SERVICE_REQUEST_CREATED"
    SERVICE_REQUEST_ASSIGNED = "SERVICE_REQUEST_ASSIGNED"
    SERVICE_REQUEST_STATUS_CHANGED = "SERVICE_REQUEST_STATUS_CHANGED"


class ExternalNotificationChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
