"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, CollectionAccountDetail, FinancePayment, permissionGranted } from "@/lib/api";

type Tab = "schedule" | "payments" | "charges" | "refunds" | "ledger";
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value));
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function CollectionDetailPage() {
  const id = String(useParams().id);
  const { session } = useAuth();
  const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const canCollect = permissionGranted(permissions, "payments.create") || permissionGranted(permissions, "payments.manage");
  const canVerify = permissionGranted(permissions, "payments.approve") || permissionGranted(permissions, "payments.manage");
  const canManage = permissionGranted(permissions, "collections.create") || permissionGranted(permissions, "collections.manage");
  const canApprove = permissionGranted(permissions, "collections.approve") || permissionGranted(permissions, "collections.manage");
  const [data, setData] = useState<CollectionAccountDetail | null>(null);
  const [tab, setTab] = useState<Tab>("schedule");
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [payment, setPayment] = useState({ amount: "", method: "BANK_TRANSFER", reference_number: "" });
  const [demand, setDemand] = useState({ installment_id: "", demand_number: "", issue_date: today(), due_date: today() });
  const [reconcile, setReconcile] = useState({ payment_id: "", received_amount: "", external_reference: "" });
  const [charge, setCharge] = useState({ installment_id: "", charge_type: "INTEREST", annual_rate_percent: "", fixed_amount: "", calculation_date: today(), reason: "" });
  const [refund, setRefund] = useState({ payment_id: "", amount: "", reason: "" });
  useEffect(() => { let live = true; apiRequest<CollectionAccountDetail>(`/collections/bookings/${id}`).then((value) => { if (live) { setData(value); setError(null); } }).catch((reason: unknown) => { if (live) setError(reason instanceof ApiError ? reason.message : "Account could not be loaded"); }); return () => { live = false; }; }, [id]);
  async function mutate(path: string, body: unknown, success: string, method = "POST") { setBusy(true); setError(null); try { const value = await apiRequest<CollectionAccountDetail>(path, { method, body: JSON.stringify(body) }); setData(value); setNotice(success); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Financial operation failed"); } finally { setBusy(false); } }
  async function submitPayment(event: FormEvent) { event.preventDefault(); await mutate(`/collections/bookings/${id}/payments`, { ...payment, reference_number: payment.reference_number || null, idempotency_key: crypto.randomUUID() }, "Payment submitted for reconciliation"); setPayment({ amount: "", method: "BANK_TRANSFER", reference_number: "" }); }
  async function submitDemand(event: FormEvent) { event.preventDefault(); await mutate(`/collections/bookings/${id}/demands`, demand, "Demand issued with server-calculated outstanding"); setDemand({ installment_id: "", demand_number: "", issue_date: today(), due_date: today() }); }
  async function submitReconciliation(event: FormEvent) { event.preventDefault(); await mutate(`/collections/payments/${reconcile.payment_id}/reconciliations`, { received_amount: reconcile.received_amount, external_reference: reconcile.external_reference || null, idempotency_key: crypto.randomUUID() }, "Reconciliation result recorded"); setReconcile({ payment_id: "", received_amount: "", external_reference: "" }); }
  async function submitCharge(event: FormEvent) { event.preventDefault(); await mutate(`/collections/installments/${charge.installment_id}/charges`, { charge_type: charge.charge_type, calculation_date: charge.calculation_date, annual_rate_percent: charge.charge_type === "INTEREST" ? charge.annual_rate_percent : null, fixed_amount: charge.charge_type === "PENALTY" ? charge.fixed_amount : null, reason: charge.reason, idempotency_key: crypto.randomUUID() }, "Server-calculated charge posted to the ledger"); }
  async function submitRefund(event: FormEvent) { event.preventDefault(); await mutate(`/collections/payments/${refund.payment_id}/refunds`, { amount: refund.amount, reason: refund.reason, idempotency_key: crypto.randomUUID() }, "Refund submitted for independent approval"); setRefund({ payment_id: "", amount: "", reason: "" }); }
  function matched(item: FinancePayment) { return data?.reconciliations.find((record) => record.payment_id === item.id)?.status === "MATCHED"; }
  if (!data) return <AppShell><main className="dashboard-content"><div className="center-inline"><span className="spinner"/>{error ?? "Loading account..."}</div></main></AppShell>;
  const account = data.account;
  return <AppShell><main className="dashboard-content collections-content"><div className="management-heading"><div><p className="overline">Collection account {account.booking_number}</p><h1>{account.customer_name}</h1><p>{account.project_name} · Unit {account.unit_number} · {data.plan_name ?? "No payment plan"}</p></div><Link href="/collections" className="button button-secondary">All accounts</Link></div>{error && <div className="alert alert-error">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}
    <section className="collection-balance"><div><span>Total value</span><strong>{money(account.total_value, account.currency)}</strong></div><div><span>Received</span><strong>{money(account.received, account.currency)}</strong></div><div><span>Outstanding</span><strong>{money(account.outstanding, account.currency)}</strong></div><div className="overdue"><span>Overdue</span><strong>{money(account.overdue, account.currency)}</strong></div></section>
    <nav className="customer-tabs booking-tabs">{(["schedule", "payments", "charges", "refunds", "ledger"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item[0].toUpperCase()+item.slice(1)}{item === "payments" ? ` (${data.payments.length})` : item === "refunds" ? ` (${data.refunds.length})` : ""}</button>)}</nav>
    {tab === "schedule" && <div className="collection-detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Installment schedule</h2><p>Status and outstanding are recalculated by the backend.</p></div></div><div className="finance-record-list">{data.installments.map((item) => <article key={item.id}><span><b>{item.sequence}</b></span><div><strong>{item.name}</strong><small>Due {new Date(item.due_date).toLocaleDateString("en-IN")}</small></div><div><strong>{money(item.outstanding, account.currency)}</strong><small>of {money(item.amount, account.currency)}</small></div><em className={`quote-status status-${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</em></article>)}</div></section>{canManage && <form className="panel finance-action-form" onSubmit={submitDemand}><h2>Issue demand</h2><p>The demand amount is the selected installment’s live outstanding; it cannot be entered here.</p><label className="field"><span>Installment</span><select required value={demand.installment_id} onChange={(event) => setDemand({ ...demand, installment_id: event.target.value })}><option value="">Select open installment</option>{data.installments.filter((item) => Number(item.outstanding)>0).map((item) => <option value={item.id} key={item.id}>{item.name} · {money(item.outstanding, account.currency)}</option>)}</select></label><label className="field"><span>Demand number</span><input required value={demand.demand_number} onChange={(event) => setDemand({ ...demand, demand_number: event.target.value.toUpperCase() })}/></label><div className="finance-form-pair"><label className="field"><span>Issue date</span><input required type="date" value={demand.issue_date} onChange={(event) => setDemand({ ...demand, issue_date: event.target.value })}/></label><label className="field"><span>Due date</span><input required type="date" min={demand.issue_date} value={demand.due_date} onChange={(event) => setDemand({ ...demand, due_date: event.target.value })}/></label></div><button className="button button-primary" disabled={busy}>Issue demand</button></form>}</div>}
    {tab === "payments" && <div className="collection-detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Payments and receipts</h2><p>Only completed payments affect the customer ledger.</p></div></div><div className="finance-payment-list">{data.payments.map((item) => <article key={item.id}><div><strong>{money(item.amount, item.currency)}</strong><small>{item.method.replaceAll("_", " ")} · {item.reference_number ?? "No reference"}</small></div><div><em className={`quote-status status-${item.status.toLowerCase()}`}>{item.status}</em><small>{item.receipt_number ?? `Submitted ${dateTime(item.paid_at ?? item.created_at)}`}</small></div>{canVerify && ["PENDING", "PROCESSING"].includes(item.status) && <div className="row-actions"><button onClick={() => setReconcile({ payment_id: item.id, received_amount: item.amount, external_reference: item.reference_number ?? "" })}>Reconcile</button>{matched(item) && <button disabled={busy} onClick={() => void mutate(`/collections/payments/${item.id}/allocate`, { installment_ids: [] }, "Payment allocated and receipt issued")}>Allocate</button>}</div>}{canCollect && item.status === "COMPLETED" && <button className="text-action" onClick={() => { setRefund({ payment_id: item.id, amount: "", reason: "" }); setTab("refunds"); }}>Refund</button>}</article>)}</div>{reconcile.payment_id && <form className="inline-finance-form" onSubmit={submitReconciliation}><strong>Reconcile payment</strong><input required type="number" min="0" step="0.01" value={reconcile.received_amount} onChange={(event) => setReconcile({ ...reconcile, received_amount: event.target.value })} placeholder="Statement amount"/><input value={reconcile.external_reference} onChange={(event) => setReconcile({ ...reconcile, external_reference: event.target.value })} placeholder="Statement reference"/><button className="button button-primary" disabled={busy}>Compare</button></form>}</section>{canCollect && <form className="panel finance-action-form" onSubmit={submitPayment}><h2>Record payment</h2><label className="field"><span>Amount received</span><input required type="number" min="0.01" step="0.01" value={payment.amount} onChange={(event) => setPayment({ ...payment, amount: event.target.value })}/></label><label className="field"><span>Method</span><select value={payment.method} onChange={(event) => setPayment({ ...payment, method: event.target.value })}><option value="BANK_TRANSFER">Bank transfer</option><option value="CHEQUE">Cheque</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="CASH">Cash</option></select></label><label className="field"><span>Reference</span><input value={payment.reference_number} onChange={(event) => setPayment({ ...payment, reference_number: event.target.value })}/></label><button className="button button-primary" disabled={busy}>Submit for reconciliation</button></form>}</div>}
    {tab === "charges" && <div className="collection-detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Penalties and interest</h2><p>Principal, elapsed days, and final amount are retained with each calculation.</p></div></div><div className="finance-record-list">{data.charges.length ? data.charges.map((item) => <article key={item.id}><span><b>{item.charge_type === "INTEREST" ? "%" : "₹"}</b></span><div><strong>{item.reason}</strong><small>{item.days_calculated} days · {item.rate_percent}% · principal {money(item.principal_amount, item.currency)}</small></div><div><strong>{money(item.amount, item.currency)}</strong><small>{item.calculation_date}</small></div><em className={`quote-status status-${item.status.toLowerCase()}`}>{item.status}</em>{canApprove && item.status === "APPLIED" && <button className="text-action" onClick={() => { const reason = window.prompt("Waiver reason"); if (reason) void mutate(`/collections/charges/${item.id}/waive`, { reason }, "Charge waived with a compensating ledger entry"); }}>Waive</button>}</article>) : <p className="muted-copy">No charges applied.</p>}</div></section>{canManage && <form className="panel finance-action-form" onSubmit={submitCharge}><h2>Calculate charge</h2><label className="field"><span>Installment</span><select required value={charge.installment_id} onChange={(event) => setCharge({ ...charge, installment_id: event.target.value })}><option value="">Select installment</option>{data.installments.filter((item) => Number(item.outstanding)>0).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Charge type</span><select value={charge.charge_type} onChange={(event) => setCharge({ ...charge, charge_type: event.target.value })}><option value="INTEREST">Annual interest</option><option value="PENALTY">Fixed penalty</option></select></label><label className="field"><span>{charge.charge_type === "INTEREST" ? "Annual rate %" : "Fixed amount"}</span><input required type="number" min="0.01" step="0.01" value={charge.charge_type === "INTEREST" ? charge.annual_rate_percent : charge.fixed_amount} onChange={(event) => charge.charge_type === "INTEREST" ? setCharge({ ...charge, annual_rate_percent: event.target.value }) : setCharge({ ...charge, fixed_amount: event.target.value })}/></label><label className="field"><span>Calculate through</span><input required type="date" value={charge.calculation_date} onChange={(event) => setCharge({ ...charge, calculation_date: event.target.value })}/></label><label className="field"><span>Contractual reason</span><textarea required rows={3} value={charge.reason} onChange={(event) => setCharge({ ...charge, reason: event.target.value })}/></label><button className="button button-primary" disabled={busy}>Calculate and post</button></form>}</div>}
    {tab === "refunds" && <div className="collection-detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Refund workflow</h2><p>Requests require a different approver before processing.</p></div></div><div className="finance-record-list">{data.refunds.length ? data.refunds.map((item) => <article key={item.id}><span><b>↩</b></span><div><strong>{money(item.amount, item.currency)}</strong><small>{item.reason ?? "No reason"}</small></div><div><em className={`quote-status status-${item.status.toLowerCase()}`}>{item.status}</em><small>{item.reference_number ?? dateTime(item.requested_at)}</small></div>{canVerify && item.status === "PENDING" && item.requested_by_user_id !== session?.user.id && <div className="row-actions"><button onClick={() => void mutate(`/collections/refunds/${item.id}/decision`, { status: "APPROVED", notes: "Refund evidence verified" }, "Refund approved")}>Approve</button><button onClick={() => void mutate(`/collections/refunds/${item.id}/decision`, { status: "REJECTED", notes: "Refund evidence rejected" }, "Refund rejected")}>Reject</button></div>}{canVerify && item.status === "PROCESSING" && <button className="text-action" onClick={() => { const reference_number = window.prompt("Refund transaction reference"); if (reference_number) void mutate(`/collections/refunds/${item.id}/process`, { reference_number }, "Refund processed and allocations reversed"); }}>Process</button>}</article>) : <p className="muted-copy">No refund requests.</p>}</div></section>{canCollect && refund.payment_id && <form className="panel finance-action-form" onSubmit={submitRefund}><h2>Request refund</h2><label className="field"><span>Amount</span><input required type="number" min="0.01" step="0.01" value={refund.amount} onChange={(event) => setRefund({ ...refund, amount: event.target.value })}/></label><label className="field"><span>Reason</span><textarea required rows={4} value={refund.reason} onChange={(event) => setRefund({ ...refund, reason: event.target.value })}/></label><button className="button button-primary" disabled={busy}>Request approval</button></form>}</div>}
    {tab === "ledger" && <section className="panel"><div className="panel-heading"><div><h2>Customer ledger</h2><p>Append-only debits, credits, charges, waivers, receipts, and refund reversals.</p></div></div><div className="ledger-list">{data.ledger.map((item) => <article key={item.id}><em className={item.entry_type === "DEBIT" ? "ledger-debit" : "ledger-credit"}>{item.entry_type}</em><div><strong>{item.description}</strong><small>{dateTime(item.posted_at)}</small></div><b>{item.entry_type === "DEBIT" ? "+" : "−"} {money(item.amount, item.currency)}</b></article>)}</div></section>}
  </main></AppShell>;
}
