"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { ProtectedRoute } from "@/components/protected-route";
import { QuotationNavigation } from "@/components/quotation-navigation";
import { apiRequest, ApiError, CostSheet, Customer, PageResponse, PriceList, Project, Unit } from "@/lib/api";

type Selection = { customer_id: string; project_id: string; unit_id: string; price_list_id: string; discount: string; final_value: string; booking: string; notes: string; amenities: string[]; premiums: string[]; parking: Record<string, number> };
const empty: Selection = { customer_id: "", project_id: "", unit_id: "", price_list_id: "", discount: "", final_value: "", booking: "", notes: "", amenities: [], premiums: [], parking: {} };
const errorText = (reason: unknown) => reason instanceof ApiError ? reason.message : "Cost sheet could not be calculated";
const money = (amount: string, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(amount));

export default function CreateQuotationPage() {
  const router = useRouter(); const { session } = useAuth();
  const [customers, setCustomers] = useState<Customer[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [priceLists, setPriceLists] = useState<PriceList[]>([]);
  const [draft, setDraft] = useState<Selection>(empty); const [preview, setPreview] = useState<CostSheet | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const selectedPriceList = useMemo(() => priceLists.find((item) => item.id === draft.price_list_id) ?? null, [draft.price_list_id, priceLists]);
  useEffect(() => { if (!session) return; let active = true; void Promise.all([apiRequest<PageResponse<Customer>>("/customers?page_size=100"), apiRequest<PageResponse<Project>>("/projects?page_size=100")]).then(([customerData, projectData]) => { if (active) { setCustomers(customerData.items); setProjects(projectData.items); } }).catch((reason: unknown) => { if (active) setError(errorText(reason)); }); return () => { active = false; }; }, [session]);
  useEffect(() => { if (!session || !draft.project_id) { setUnits([]); setPriceLists([]); return; } let active = true; void Promise.all([apiRequest<PageResponse<Unit>>(`/inventory/units?project_id=${draft.project_id}&page_size=100`), apiRequest<PageResponse<PriceList>>(`/price-lists?project_id=${draft.project_id}&status=ACTIVE&page_size=100`)]).then(([unitData, listData]) => { if (active) { setUnits(unitData.items); setPriceLists(listData.items); } }).catch((reason: unknown) => { if (active) setError(errorText(reason)); }); return () => { active = false; }; }, [draft.project_id, session]);
  const set = <K extends keyof Selection>(key: K, value: Selection[K]) => { setDraft((current) => ({ ...current, [key]: value })); setPreview(null); };
  function payload() { return { customer_id: draft.customer_id, unit_id: draft.unit_id, price_list_id: draft.price_list_id, parking: Object.entries(draft.parking).filter(([, quantity]) => quantity > 0).map(([code, quantity]) => ({ code, quantity })), amenity_codes: draft.amenities, optional_premium_codes: draft.premiums, requested_discount_amount: draft.final_value ? "0" : draft.discount || "0", final_agreed_value: draft.final_value || null, booking_amount_override: draft.booking || null, request_notes: draft.notes || null }; }
  async function calculate(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { setPreview(await apiRequest<CostSheet>("/cost-sheets/preview", { method: "POST", body: JSON.stringify(payload()) })); } catch (reason) { setError(errorText(reason)); } finally { setLoading(false); } }
  async function save() { setSaving(true); setError(null); try { const sheet = await apiRequest<CostSheet>("/cost-sheets", { method: "POST", body: JSON.stringify(payload()) }); router.push(`/cost-sheets/${sheet.id}`); } catch (reason) { setError(errorText(reason)); } finally { setSaving(false); } }
  function toggle(key: "amenities" | "premiums", code: string) { set(key, draft[key].includes(code) ? draft[key].filter((item) => item !== code) : [...draft[key], code]); }
  return <ProtectedRoute permission="quotations.create"><AppShell><main className="dashboard-content quote-content"><div className="management-heading"><div><p className="overline">Guided pricing</p><h1>Build a cost sheet</h1><p>Select the customer and inventory first. All totals are calculated and validated by the backend.</p></div><Link className="button button-secondary" href="/quotations">Cancel</Link></div><QuotationNavigation />{error && <div className="alert alert-error page-alert">{error}</div>}
    <div className="cost-builder"><form className="panel cost-form" onSubmit={calculate}><div className="workflow-steps"><span className="active">1 Customer</span><span className={draft.project_id ? "active" : ""}>2 Unit</span><span className={draft.price_list_id ? "active" : ""}>3 Price list</span><span className={preview ? "active" : ""}>4 Review</span></div><section><h2>Customer & property</h2><div className="lead-form-grid"><label className="field span-two"><span>Customer</span><select required value={draft.customer_id} onChange={(e) => set("customer_id", e.target.value)}><option value="">Select customer</option>{customers.map((item) => <option value={item.id} key={item.id}>{item.full_name} · {item.phone ?? item.email ?? "No contact"}</option>)}</select></label><label className="field"><span>Project</span><select required value={draft.project_id} onChange={(e) => { setDraft((current) => ({ ...current, project_id: e.target.value, unit_id: "", price_list_id: "", amenities: [], premiums: [], parking: {} })); setPreview(null); }}><option value="">Select project</option>{projects.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Unit</span><select required disabled={!draft.project_id} value={draft.unit_id} onChange={(e) => set("unit_id", e.target.value)}><option value="">Select unit</option>{units.map((item) => <option value={item.id} key={item.id}>{item.unit_number} · {item.unit_type ?? "Unspecified"} · {item.status.replaceAll("_", " ")}</option>)}</select></label><label className="field span-two"><span>Active price list</span><select required disabled={!draft.project_id} value={draft.price_list_id} onChange={(e) => { setDraft((current) => ({ ...current, price_list_id: e.target.value, amenities: [], premiums: [], parking: {} })); setPreview(null); }}><option value="">Select price list</option>{priceLists.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.code} v{item.version}</option>)}</select></label></div></section>
      {selectedPriceList && <section><h2>Options & negotiation</h2><div className="option-groups">{selectedPriceList.pricing_rules.optional_premium_codes}{selectedPriceList.pricing_rules.premiums.filter((item) => item.optional).length > 0 && <fieldset><legend>Optional premiums</legend>{selectedPriceList.pricing_rules.premiums.filter((item) => item.optional).map((item) => <label key={item.code}><input type="checkbox" checked={draft.premiums.includes(item.code)} onChange={() => toggle("premiums", item.code)}/><span><strong>{item.label}</strong><small>{item.calculation.replace("_", " ")} · {item.value}</small></span></label>)}</fieldset>}{selectedPriceList.pricing_rules.amenity_charges.length > 0 && <fieldset><legend>Amenities</legend>{selectedPriceList.pricing_rules.amenity_charges.map((item) => <label key={item.code}><input type="checkbox" checked={draft.amenities.includes(item.code)} onChange={() => toggle("amenities", item.code)}/><span><strong>{item.label}</strong><small>{item.calculation.replace("_", " ")} · {item.value}</small></span></label>)}</fieldset>}{selectedPriceList.pricing_rules.parking_options.length > 0 && <fieldset><legend>Parking</legend>{selectedPriceList.pricing_rules.parking_options.map((item) => <label key={item.code}><span><strong>{item.label}</strong><small>{item.calculation.replace("_", " ")} · {item.value}</small></span><input aria-label={`${item.label} quantity`} type="number" min="0" max="100" value={draft.parking[item.code] ?? 0} onChange={(e) => set("parking", { ...draft.parking, [item.code]: Number(e.target.value) })}/></label>)}</fieldset>}</div><div className="lead-form-grid negotiation-grid"><label className="field"><span>Requested discount</span><input type="number" min="0" step="0.01" disabled={Boolean(draft.final_value)} value={draft.discount} onChange={(e) => set("discount", e.target.value)}/></label><label className="field"><span>Or final agreed value</span><input type="number" min="0" step="0.01" disabled={Boolean(draft.discount)} value={draft.final_value} onChange={(e) => set("final_value", e.target.value)}/></label><label className="field"><span>Booking amount override</span><input type="number" min="0" step="0.01" value={draft.booking} onChange={(e) => set("booking", e.target.value)} placeholder="Use configured rule"/></label><label className="field span-two"><span>Approval notes</span><textarea maxLength={2000} rows={3} value={draft.notes} onChange={(e) => set("notes", e.target.value)}/></label></div></section>}
      <div className="form-actions"><button disabled={loading || !draft.price_list_id} className="button button-primary">{loading ? "Calculating..." : "Preview cost sheet"}</button></div></form>
      <aside className="panel cost-preview"><div className="panel-heading"><div><p className="overline">Server-calculated</p><h2>Commercial summary</h2></div></div>{preview ? <><div className="cost-lines">{preview.items.map((item) => <div key={`${item.sequence}-${item.label}`}><span><strong>{item.label}</strong><small>{item.category.replaceAll("_", " ")} · {item.quantity} × {item.rate}</small></span><b>{money(item.amount, preview.currency)}</b></div>)}</div><dl className="cost-totals"><div><dt>Gross value</dt><dd>{money(preview.gross_value, preview.currency)}</dd></div><div className="discount"><dt>Discount</dt><dd>− {money(preview.discount_amount, preview.currency)}</dd></div><div><dt>Taxes</dt><dd>{money(preview.tax_amount, preview.currency)}</dd></div><div className="total"><dt>Final agreed value</dt><dd>{money(preview.final_agreed_value, preview.currency)}</dd></div><div><dt>Booking amount</dt><dd>{money(preview.booking_amount, preview.currency)}</dd></div></dl><div className="preview-status"><span className={`quote-status status-${preview.status.toLowerCase()}`}>{preview.status.replaceAll("_", " ")}</span><small>{preview.status === "PENDING_APPROVAL" ? "Discount exceeds the self-approval threshold." : "Cost sheet can proceed to quotation after save."}</small></div><button type="button" onClick={() => void save()} disabled={saving} className="button button-primary button-wide">{saving ? "Saving..." : "Save cost sheet"}</button></> : <div className="preview-placeholder"><span>₹</span><strong>Your itemized cost sheet appears here</strong><p>No totals are calculated in the browser.</p></div>}</aside>
    </div>
  </main></AppShell></ProtectedRoute>;
}
