"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, CostSheet, permissionGranted, Quotation } from "@/lib/api";

const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Cost sheet is unavailable";
const money = (amount: string, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(amount));

export default function CostSheetDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [sheet, setSheet] = useState<CostSheet | null>(null); const [refresh, setRefresh] = useState(0); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [notes, setNotes] = useState(""); const [validUntil, setValidUntil] = useState("");
  const canApprove = permissionGranted(permissions, "quotations.approve"); const canCreate = permissionGranted(permissions, "quotations.create");
  useEffect(() => { if (!session || !id) return; let active = true; void apiRequest<CostSheet>(`/cost-sheets/${id}`).then((data) => { if (active) setSheet(data); }).catch((reason: unknown) => { if (active) setError(message(reason)); }); return () => { active = false; }; }, [id, refresh, session]);
  async function decide(status: "APPROVED" | "REJECTED") { setSaving(true); setError(null); try { await apiRequest(`/cost-sheets/${id}/approval`, { method: "POST", body: JSON.stringify({ status, notes: notes || null }) }); setNotice(`Discount request ${status.toLowerCase()}`); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function createQuotation(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const quote = await apiRequest<Quotation>("/quotations", { method: "POST", body: JSON.stringify({ cost_sheet_id: id, valid_until: validUntil }) }); router.push(`/quotations/${quote.id}`); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  if (!sheet) return <AppShell><main className="dashboard-content"><div className="center-inline"><span className="spinner"/>Loading cost sheet...</div>{error && <div className="alert alert-error">{error}</div>}</main></AppShell>;
  return <AppShell><main className="dashboard-content quote-content"><Link className="back-link" href="/quotations">← Quotations</Link><div className="quote-detail-head"><div><p className="overline">Cost sheet · {sheet.price_list_name} v{sheet.price_list_version}</p><h1>{sheet.customer_name}</h1><p>{sheet.project_name} · Unit {sheet.unit_number}</p></div><span className={`quote-status status-${sheet.status.toLowerCase()}`}>{sheet.status.replaceAll("_", " ")}</span></div>{error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}
    <div className="quote-detail-grid"><div className="quote-main-stack"><section className="panel"><div className="panel-heading"><div><h2>Itemized pricing</h2><p>Values are frozen from the selected price-list version.</p></div></div><div className="detail-line-table"><div className="detail-line head"><span>Component</span><span>Basis</span><span>Amount</span></div>{sheet.items.map((item) => <div className="detail-line" key={`${item.sequence}-${item.label}`}><span><strong>{item.label}</strong><small>{item.category.replaceAll("_", " ")}{item.taxable ? " · Taxable" : ""}</small></span><span>{item.quantity} × {item.rate}</span><span>{money(item.amount, sheet.currency)}</span></div>)}</div></section>
      {sheet.approval && <section className="panel approval-card"><div className="panel-heading"><div><h2>Discount approval</h2><p>Requested by {sheet.approval.requested_by_name ?? "User"} · {new Date(sheet.approval.created_at).toLocaleString("en-IN")}</p></div><span className={`quote-status status-${sheet.approval.status.toLowerCase()}`}>{sheet.approval.status}</span></div><dl className="customer-facts"><div><dt>Approval matrix level</dt><dd>{sheet.approval.approval_level_name}</dd></div><div><dt>Requested amount</dt><dd>{money(sheet.approval.requested_discount_amount, sheet.currency)}</dd></div><div><dt>Requested percent</dt><dd>{sheet.approval.requested_discount_percent}%</dd></div><div><dt>Self-approval limit</dt><dd>{sheet.approval.self_approval_limit_percent}%</dd></div><div><dt>Previous value</dt><dd>{money(sheet.approval.previous_value, sheet.currency)}</dd></div><div><dt>Final approved value</dt><dd>{sheet.approval.final_approved_value ? money(sheet.approval.final_approved_value, sheet.currency) : "Pending decision"}</dd></div><div><dt>Approver</dt><dd>{sheet.approval.approver_name ?? "Pending"}</dd></div><div><dt>Decision timestamp</dt><dd>{sheet.approval.decided_at ? new Date(sheet.approval.decided_at).toLocaleString("en-IN") : "Pending"}</dd></div></dl>{sheet.approval.request_notes && <p className="project-description"><strong>Reason:</strong> {sheet.approval.request_notes}</p>}{sheet.approval.status === "PENDING" && canApprove && <div className="approval-actions"><label className="field"><span>Decision notes</span><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)}/></label><div><button disabled={saving} className="button button-danger" onClick={() => void decide("REJECTED")}>Reject</button><button disabled={saving} className="button button-primary" onClick={() => void decide("APPROVED")}>Approve discount</button></div></div>}{sheet.approval.decision_notes && <p className="decision-note"><strong>Decision:</strong> {sheet.approval.decision_notes}</p>}</section>}
    </div><aside className="quote-side-stack"><section className="panel commercial-total"><p className="overline">Commercial summary</p><dl><div><dt>Base price</dt><dd>{money(sheet.base_price, sheet.currency)}</dd></div><div><dt>Gross value</dt><dd>{money(sheet.gross_value, sheet.currency)}</dd></div><div className="discount"><dt>Discount</dt><dd>− {money(sheet.discount_amount, sheet.currency)}</dd></div><div><dt>Taxes</dt><dd>{money(sheet.tax_amount, sheet.currency)}</dd></div><div className="total"><dt>Final agreed value</dt><dd>{money(sheet.final_agreed_value, sheet.currency)}</dd></div><div><dt>Booking amount</dt><dd>{money(sheet.booking_amount, sheet.currency)}</dd></div></dl></section>
      <section className="panel"><p className="overline">Next action</p>{sheet.quotation_id ? <Link className="button button-primary button-wide" href={`/quotations/${sheet.quotation_id}`}>Open quotation</Link> : sheet.status === "APPROVED" && canCreate ? <form className="form-stack" onSubmit={createQuotation}><label className="field"><span>Quotation valid until</span><input required type="date" min={new Date().toISOString().slice(0, 10)} value={validUntil} onChange={(event) => setValidUntil(event.target.value)}/></label><button disabled={saving} className="button button-primary">{saving ? "Creating..." : "Create quotation"}</button></form> : <p className="muted-copy">{sheet.status === "PENDING_APPROVAL" ? "Approval is required before quotation creation." : "No quotation action is available in this status."}</p>}</section><section className="panel"><p className="overline">Record details</p><dl className="customer-side-facts"><div><dt>Created by</dt><dd>{sheet.created_by_name}</dd></div><div><dt>Created</dt><dd>{sheet.created_at ? new Date(sheet.created_at).toLocaleString("en-IN") : "Preview"}</dd></div><div><dt>Price list</dt><dd>{sheet.price_list_name} v{sheet.price_list_version}</dd></div></dl></section>
    </aside></div>
  </main></AppShell>;
}
