"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiRequest, ApiError, permissionGranted, SalespersonOption, SiteVisit } from "@/lib/api";

function message(reason: unknown) { return reason instanceof ApiError ? reason.message : "Site visit is unavailable"; }
function dateTime(value: string | null) { return value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded"; }
function localInput(value: string) { const date = new Date(value); const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16); }

export default function SiteVisitDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [visit, setVisit] = useState<SiteVisit | null>(null); const [salespeople, setSalespeople] = useState<SalespersonOption[]>([]); const [refresh, setRefresh] = useState(0); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [mode, setMode] = useState<"edit" | "checkin" | "checkout" | null>(null);
  const [edit, setEdit] = useState({ scheduled_at: "", assigned_user_id: "", attendees: "", notes: "" }); const [checkout, setCheckout] = useState({ feedback: "", outcome: "", next_follow_up_at: "" });
  const canUpdate = permissionGranted(permissions, "visits.update"); const canDelete = permissionGranted(permissions, "visits.delete"); const canAssign = permissionGranted(permissions, "visits.assign");

  useEffect(() => { if (!session || !id) return; let active = true; void apiRequest<SiteVisit>(`/site-visits/${id}`).then((data) => { if (!active) return; setVisit(data); setEdit({ scheduled_at: localInput(data.scheduled_at), assigned_user_id: data.assigned_user_id ?? "", attendees: data.attendees.join(", "), notes: data.notes ?? "" }); }).catch((reason: unknown) => { if (active) setError(message(reason)); }); return () => { active = false; }; }, [id, refresh, session]);
  useEffect(() => { if (!session || !canAssign) return; let active = true; void apiRequest<SalespersonOption[]>("/site-visits/salespeople").then((data) => { if (active) setSalespeople(data); }).catch(() => undefined); return () => { active = false; }; }, [canAssign, session]);

  async function action(path: string, body: Record<string, unknown>, success: string) { setSaving(true); setError(null); try { await apiRequest(`/site-visits/${id}/${path}`, { method: "POST", body: JSON.stringify(body) }); setMode(null); setNotice(success); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function changeStatus(status: "CONFIRMED" | "CANCELLED" | "NO_SHOW") { const reason = status === "CANCELLED" ? window.prompt("Cancellation reason (optional)") : null; if (status === "CANCELLED" && reason === null) return; await action("status", { status, reason }, `Visit marked ${status.replaceAll("_", " ").toLowerCase()}`); }
  async function saveEdit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await apiRequest(`/site-visits/${id}`, { method: "PATCH", body: JSON.stringify({ scheduled_at: new Date(edit.scheduled_at).toISOString(), assigned_user_id: edit.assigned_user_id || null, attendees: edit.attendees.split(",").map((item) => item.trim()).filter(Boolean), notes: edit.notes || null }) }); setMode(null); setNotice("Visit details updated"); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function submitCheckout(event: FormEvent) { event.preventDefault(); await action("check-out", { feedback: checkout.feedback || null, outcome: checkout.outcome, next_follow_up_at: checkout.next_follow_up_at ? new Date(checkout.next_follow_up_at).toISOString() : null }, "Visit completed and timelines updated"); }
  async function remove() { if (!confirm("Delete this site visit?")) return; try { await apiRequest(`/site-visits/${id}`, { method: "DELETE" }); router.push("/site-visits"); } catch (reason) { setError(message(reason)); } }

  if (!visit) return <AppShell><main className="dashboard-content"><div className="center-inline"><span className="spinner" />Loading site visit...</div>{error && <div className="alert alert-error">{error}</div>}</main></AppShell>;
  const editable = ["SCHEDULED", "CONFIRMED"].includes(visit.status);
  return <AppShell><main className="dashboard-content visit-content"><Link className="back-link" href="/site-visits">← Site visits</Link><div className="visit-detail-head"><div><p className="overline">{visit.project_name}</p><h1>{visit.customer_name ?? visit.lead_name}</h1><p>{dateTime(visit.scheduled_at)} · {visit.assigned_user_name ?? "Unassigned"}</p></div><div className="heading-actions"><em className={`visit-status status-${visit.status.toLowerCase()}`}>{visit.status.replaceAll("_", " ")}</em>{editable && canUpdate && <button className="button button-secondary" onClick={() => setMode("edit")}>Edit</button>}{canDelete && ["SCHEDULED", "CANCELLED"].includes(visit.status) && <button className="button button-danger" onClick={() => void remove()}>Delete</button>}</div></div>{error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}
    {canUpdate && <section className="visit-action-bar"><div><strong>Visit workflow</strong><span>Actions follow an enforced lifecycle and are audit logged.</span></div>{visit.status === "SCHEDULED" && <button onClick={() => void changeStatus("CONFIRMED")}>Confirm</button>}{["SCHEDULED", "CONFIRMED"].includes(visit.status) && <button className="primary" onClick={() => setMode("checkin")}>Check in</button>}{["SCHEDULED", "CONFIRMED"].includes(visit.status) && <button onClick={() => void changeStatus("NO_SHOW")}>No-show</button>}{["SCHEDULED", "CONFIRMED"].includes(visit.status) && <button className="danger" onClick={() => void changeStatus("CANCELLED")}>Cancel</button>}{visit.status === "CHECKED_IN" && <button className="primary" onClick={() => setMode("checkout")}>Check out & complete</button>}</section>}
    <div className="visit-detail-grid"><div className="visit-main-stack"><section className="panel"><div className="panel-heading"><div><h2>Visit plan</h2><p>Appointment, project, units, and attendees.</p></div><Link href="/calendar">Open calendar</Link></div><dl className="customer-facts"><div><dt>Scheduled</dt><dd>{dateTime(visit.scheduled_at)}</dd></div><div><dt>Salesperson</dt><dd>{visit.assigned_user_name ?? "Unassigned"}</dd></div><div><dt>Project</dt><dd><Link href={`/projects/${visit.project_id}`}>{visit.project_name}</Link></dd></div><div><dt>Attendees</dt><dd>{visit.attendees.join(", ") || "Not specified"}</dd></div><div><dt>Lead</dt><dd>{visit.lead_id ? <Link href={`/leads/${visit.lead_id}`}>{visit.lead_name}</Link> : "Not linked"}</dd></div><div><dt>Customer</dt><dd>{visit.customer_id ? <Link href={`/customers/${visit.customer_id}`}>{visit.customer_name}</Link> : "Not linked"}</dd></div></dl>{visit.notes && <p className="project-description">{visit.notes}</p>}</section><section className="panel"><div className="panel-heading"><div><h2>Interested units</h2><p>Units shortlisted for this visit.</p></div></div><div className="visit-unit-list">{visit.interested_units.map((unit) => <article key={unit.id}><span><strong>{unit.unit_number}</strong><small>{[unit.tower_name, unit.floor_name, unit.unit_type].filter(Boolean).join(" · ")}</small></span><em className={`inventory-status status-${unit.status.toLowerCase()}`}>{unit.status.replaceAll("_", " ")}</em></article>)}{!visit.interested_units.length && <p className="muted-copy">No specific units were shortlisted.</p>}</div></section>{visit.status === "COMPLETED" && <section className="panel"><div className="panel-heading"><div><h2>Feedback & outcome</h2><p>Visit result carried into the sales timeline.</p></div></div><dl className="customer-facts"><div><dt>Outcome</dt><dd>{visit.outcome}</dd></div><div><dt>Next follow-up</dt><dd>{dateTime(visit.next_follow_up_at)}</dd></div></dl>{visit.feedback && <p className="project-description">{visit.feedback}</p>}</section>}</div><aside className="visit-side-stack"><section className="panel visit-progress"><p className="overline">Visit activity</p><div><span className={visit.check_in_at ? "done" : ""} /><p><strong>Check-in</strong><small>{dateTime(visit.check_in_at)}</small></p></div><div><span className={visit.check_out_at ? "done" : ""} /><p><strong>Check-out</strong><small>{dateTime(visit.check_out_at)}</small></p></div><div><span className={visit.completed_at ? "done" : ""} /><p><strong>Completed</strong><small>{dateTime(visit.completed_at)}</small></p></div></section><section className="panel"><p className="overline">Record ownership</p><dl className="customer-side-facts"><div><dt>Created by</dt><dd>{visit.created_by_user_name ?? "System"}</dd></div><div><dt>Created</dt><dd>{dateTime(visit.created_at)}</dd></div><div><dt>Last updated</dt><dd>{dateTime(visit.updated_at)}</dd></div></dl></section></aside></div>
    {mode === "edit" && <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={saveEdit}><div className="modal-heading"><h2>Edit visit</h2><button type="button" className="icon-button" onClick={() => setMode(null)}>×</button></div><div className="customer-edit-scroll form-stack"><label className="field"><span>Visit date & time</span><input required type="datetime-local" value={edit.scheduled_at} onChange={(e) => setEdit({ ...edit, scheduled_at: e.target.value })} /></label>{canAssign && <label className="field"><span>Salesperson</span><select value={edit.assigned_user_id} onChange={(e) => setEdit({ ...edit, assigned_user_id: e.target.value })}>{salespeople.map((item) => <option value={item.id} key={item.id}>{item.full_name}</option>)}</select></label>}<label className="field"><span>Attendees</span><input value={edit.attendees} onChange={(e) => setEdit({ ...edit, attendees: e.target.value })} /></label><label className="field"><span>Notes</span><textarea rows={4} value={edit.notes} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} /></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setMode(null)}>Cancel</button><button className="button button-primary" disabled={saving}>Save changes</button></div></form></div>}
    {mode === "checkin" && <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={(event) => { event.preventDefault(); void action("check-in", { attendees: edit.attendees.split(",").map((item) => item.trim()).filter(Boolean) }, "Visitor checked in"); }}><div className="modal-heading"><h2>Check in visitors</h2><button type="button" className="icon-button" onClick={() => setMode(null)}>×</button></div><div className="customer-edit-scroll form-stack"><label className="field"><span>Actual attendees</span><input value={edit.attendees} onChange={(e) => setEdit({ ...edit, attendees: e.target.value })} placeholder="Names separated by commas" /></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setMode(null)}>Cancel</button><button className="button button-primary" disabled={saving}>Check in now</button></div></form></div>}
    {mode === "checkout" && <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={submitCheckout}><div className="modal-heading"><h2>Complete visit</h2><button type="button" className="icon-button" onClick={() => setMode(null)}>×</button></div><div className="customer-edit-scroll form-stack"><label className="field"><span>Outcome</span><input required minLength={2} value={checkout.outcome} onChange={(e) => setCheckout({ ...checkout, outcome: e.target.value })} placeholder="Interested, revisit requested..." /></label><label className="field"><span>Feedback</span><textarea rows={5} value={checkout.feedback} onChange={(e) => setCheckout({ ...checkout, feedback: e.target.value })} /></label><label className="field"><span>Next follow-up</span><input type="datetime-local" value={checkout.next_follow_up_at} onChange={(e) => setCheckout({ ...checkout, next_follow_up_at: e.target.value })} /></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setMode(null)}>Cancel</button><button className="button button-primary" disabled={saving}>Check out & complete</button></div></form></div>}
  </main></AppShell>;
}
