"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { useConfirmDialog } from "@/components/confirm-dialog";
import { apiRequest, ApiError, Floor, PageResponse, permissionGranted, Project, ProjectStatus, Tower, Unit } from "@/lib/api";

type Tab = "overview" | "hierarchy" | "units";
type HierarchyDraft = { kind: "tower" | "floor"; id: string | null; name: string; code: string; tower_id: string; floor_number: string; is_active: boolean };
type UnitDraft = { id: string | null; tower_id: string; floor_id: string; unit_number: string; unit_type: string; area_sqft: string; carpet_area_sqft: string; built_up_area_sqft: string; facing: string; bedrooms: string; bathrooms: string; balconies: string; base_price: string; currency: string; amenities: string; price_components: string; configuration: string };
const statuses: ProjectStatus[] = ["PLANNING", "LAUNCHED", "UNDER_CONSTRUCTION", "COMPLETED", "ON_HOLD", "ARCHIVED"];
const blankUnit: UnitDraft = { id: null, tower_id: "", floor_id: "", unit_number: "", unit_type: "", area_sqft: "", carpet_area_sqft: "", built_up_area_sqft: "", facing: "", bedrooms: "", bathrooms: "", balconies: "", base_price: "", currency: "INR", amenities: "", price_components: "{}", configuration: "{}" };
function message(reason: unknown) { return reason instanceof ApiError ? reason.message : "Project configuration is unavailable"; }
function parseJson(value: string, label: string): Record<string, unknown> | null { if (!value.trim()) return null; const parsed: unknown = JSON.parse(value); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error(`${label} must be a JSON object`); return parsed as Record<string, unknown>; }

export default function ProjectDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { session } = useAuth(); const confirmDialog = useConfirmDialog();
  const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [project, setProject] = useState<Project | null>(null); const [towers, setTowers] = useState<Tower[]>([]); const [floors, setFloors] = useState<Floor[]>([]); const [units, setUnits] = useState<Unit[]>([]);
  const [tab, setTab] = useState<Tab>("overview"); const [refresh, setRefresh] = useState(0); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [editingProject, setEditingProject] = useState(false); const [projectDraft, setProjectDraft] = useState<Record<string, string>>({});
  const [hierarchyDraft, setHierarchyDraft] = useState<HierarchyDraft | null>(null); const [unitDraft, setUnitDraft] = useState<UnitDraft | null>(null); const [saving, setSaving] = useState(false);
  const canUpdateProject = permissionGranted(permissions, "projects.update"); const canDeleteProject = permissionGranted(permissions, "projects.delete"); const canCreateHierarchy = permissionGranted(permissions, "projects.create");
  const canCreateUnit = permissionGranted(permissions, "inventory.create"); const canUpdateUnit = permissionGranted(permissions, "inventory.update"); const canDeleteUnit = permissionGranted(permissions, "inventory.delete");

  useEffect(() => {
    if (!session || !id) return; let active = true;
    void Promise.all([apiRequest<Project>(`/projects/${id}`), apiRequest<Tower[]>(`/projects/${id}/towers`), apiRequest<Floor[]>(`/projects/${id}/floors`), apiRequest<PageResponse<Unit>>(`/inventory/units?project_id=${id}&page_size=100`)]).then(([projectData, towerData, floorData, unitData]) => { if (!active) return; setProject(projectData); setTowers(towerData); setFloors(floorData); setUnits(unitData.items); setProjectDraft({ name: projectData.name, description: projectData.description ?? "", project_type: projectData.project_type ?? "", address_line1: projectData.address_line1 ?? "", address_line2: projectData.address_line2 ?? "", city: projectData.city ?? "", state: projectData.state ?? "", postal_code: projectData.postal_code ?? "", country: projectData.country ?? "", rera_number: projectData.rera_number ?? "", launch_date: projectData.launch_date ?? "", expected_possession_date: projectData.expected_possession_date ?? "", default_currency: projectData.default_currency, amenities: (projectData.amenities ?? []).join(", "), configuration: JSON.stringify(projectData.configuration ?? {}, null, 2), status: projectData.status }); }).catch((reason: unknown) => { if (active) setError(message(reason)); });
    return () => { active = false; };
  }, [id, refresh, session]);

  async function saveProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { await apiRequest<Project>(`/projects/${id}`, { method: "PATCH", body: JSON.stringify({ ...projectDraft, description: projectDraft.description || null, project_type: projectDraft.project_type || null, address_line1: projectDraft.address_line1 || null, address_line2: projectDraft.address_line2 || null, city: projectDraft.city || null, state: projectDraft.state || null, postal_code: projectDraft.postal_code || null, country: projectDraft.country || null, rera_number: projectDraft.rera_number || null, launch_date: projectDraft.launch_date || null, expected_possession_date: projectDraft.expected_possession_date || null, amenities: projectDraft.amenities.split(",").map((item) => item.trim()).filter(Boolean), configuration: parseJson(projectDraft.configuration, "Configuration") }) }); setEditingProject(false); setNotice("Project configuration updated"); setRefresh((value) => value + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : message(reason)); } finally { setSaving(false); } }
  async function deleteProject() { if (!(await confirmDialog({ title: "Delete project?", message: "The project and any unused hierarchy will be permanently removed. Referenced inventory prevents deletion.", confirmLabel: "Delete project", tone: "danger" }))) return; try { await apiRequest<void>(`/projects/${id}`, { method: "DELETE" }); router.push("/projects"); } catch (reason) { setError(message(reason)); } }

  function openTower(item?: Tower) { setHierarchyDraft({ kind: "tower", id: item?.id ?? null, name: item?.name ?? "", code: item?.code ?? "", tower_id: "", floor_number: "", is_active: item?.is_active ?? true }); }
  function openFloor(item?: Floor) { setHierarchyDraft({ kind: "floor", id: item?.id ?? null, name: item?.name ?? "", code: "", tower_id: item?.tower_id ?? towers[0]?.id ?? "", floor_number: item ? String(item.floor_number) : "", is_active: item?.is_active ?? true }); }
  async function saveHierarchy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!hierarchyDraft) return; setSaving(true); setError(null); try { const isTower = hierarchyDraft.kind === "tower"; const path = isTower ? `/projects/${id}/towers${hierarchyDraft.id ? `/${hierarchyDraft.id}` : ""}` : `/projects/${id}/floors${hierarchyDraft.id ? `/${hierarchyDraft.id}` : ""}`; const payload = isTower ? { name: hierarchyDraft.name, code: hierarchyDraft.code, is_active: hierarchyDraft.is_active } : { ...(hierarchyDraft.id ? {} : { tower_id: hierarchyDraft.tower_id }), name: hierarchyDraft.name, floor_number: Number(hierarchyDraft.floor_number), is_active: hierarchyDraft.is_active }; await apiRequest(path, { method: hierarchyDraft.id ? "PATCH" : "POST", body: JSON.stringify(payload) }); setHierarchyDraft(null); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function deleteHierarchy(kind: "towers" | "floors", entityId: string) { if (!(await confirmDialog({ title: `Delete ${kind.slice(0, -1)}?`, message: "This hierarchy record will be permanently removed if it has no referenced inventory.", confirmLabel: "Delete", tone: "danger" }))) return; try { await apiRequest<void>(`/projects/${id}/${kind}/${entityId}`, { method: "DELETE" }); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } }

  function openUnit(item?: Unit) { setUnitDraft(item ? { id: item.id, tower_id: item.tower_id ?? "", floor_id: item.floor_id ?? "", unit_number: item.unit_number, unit_type: item.unit_type ?? "", area_sqft: item.area_sqft ?? "", carpet_area_sqft: item.carpet_area_sqft ?? "", built_up_area_sqft: item.built_up_area_sqft ?? "", facing: item.facing ?? "", bedrooms: item.bedrooms == null ? "" : String(item.bedrooms), bathrooms: item.bathrooms == null ? "" : String(item.bathrooms), balconies: item.balconies == null ? "" : String(item.balconies), base_price: item.base_price ?? "", currency: item.currency ?? project?.default_currency ?? "INR", amenities: (item.amenities ?? []).join(", "), price_components: JSON.stringify(item.price_components ?? {}, null, 2), configuration: JSON.stringify(item.configuration ?? {}, null, 2) } : { ...blankUnit, currency: project?.default_currency ?? "INR", tower_id: towers[0]?.id ?? "" }); }
  async function saveUnit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!unitDraft) return; setSaving(true); setError(null); try { const numeric = ["area_sqft", "carpet_area_sqft", "built_up_area_sqft", "bedrooms", "bathrooms", "balconies", "base_price"] as const; const payload: Record<string, unknown> = { ...unitDraft, id: undefined, tower_id: unitDraft.tower_id || null, floor_id: unitDraft.floor_id || null, unit_type: unitDraft.unit_type || null, facing: unitDraft.facing || null, currency: unitDraft.base_price ? unitDraft.currency : null, amenities: unitDraft.amenities.split(",").map((item) => item.trim()).filter(Boolean), price_components: parseJson(unitDraft.price_components, "Price components"), configuration: parseJson(unitDraft.configuration, "Configuration") }; for (const field of numeric) payload[field] = unitDraft[field] === "" ? null : Number(unitDraft[field]); await apiRequest<Unit>(unitDraft.id ? `/inventory/units/${unitDraft.id}` : `/projects/${id}/units`, { method: unitDraft.id ? "PATCH" : "POST", body: JSON.stringify(payload) }); setUnitDraft(null); setRefresh((value) => value + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : message(reason)); } finally { setSaving(false); } }
  async function deleteUnit(unitId: string) { if (!(await confirmDialog({ title: "Delete unit?", message: "This unit will be permanently removed if it has no holds, quotations, or bookings.", confirmLabel: "Delete unit", tone: "danger" }))) return; try { await apiRequest<void>(`/inventory/units/${unitId}`, { method: "DELETE" }); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } }

  if (!project) return <AppShell><main className="dashboard-content"><div className="center-inline"><span className="spinner" />Loading project...</div>{error && <div className="alert alert-error">{error}</div>}</main></AppShell>;
  return <AppShell><main className="dashboard-content inventory-content"><Link href="/projects" className="back-link">← Projects</Link><div className="project-detail-head"><div><p className="overline">{project.code}</p><h1>{project.name}</h1><p>{[project.project_type, project.city, project.state].filter(Boolean).join(" · ") || "Project configuration"}</p></div><div className="heading-actions"><span className={`inventory-status status-${project.status.toLowerCase()}`}>{project.status.replaceAll("_", " ")}</span>{canUpdateProject && <button className="button button-secondary" onClick={() => setEditingProject(true)}>Edit configuration</button>}{canDeleteProject && <button className="button button-danger" onClick={() => void deleteProject()}>Delete</button>}</div></div>{error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}<nav className="customer-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Overview</button><button className={tab === "hierarchy" ? "active" : ""} onClick={() => setTab("hierarchy")}>Towers & floors</button><button className={tab === "units" ? "active" : ""} onClick={() => setTab("units")}>Units</button></nav>
    {tab === "overview" && <div className="project-overview"><section className="panel"><div className="panel-heading"><div><h2>Project configuration</h2><p>Registration, timeline, address, amenities, and custom settings.</p></div></div><dl className="customer-facts"><div><dt>RERA number</dt><dd>{project.rera_number ?? "Not captured"}</dd></div><div><dt>Default currency</dt><dd>{project.default_currency}</dd></div><div><dt>Launch date</dt><dd>{project.launch_date ?? "Not captured"}</dd></div><div><dt>Expected possession</dt><dd>{project.expected_possession_date ?? "Not captured"}</dd></div><div><dt>Address</dt><dd>{[project.address_line1, project.address_line2, project.city, project.state, project.postal_code, project.country].filter(Boolean).join(", ") || "Not captured"}</dd></div><div><dt>Amenities</dt><dd>{project.amenities?.join(", ") || "Not configured"}</dd></div></dl>{project.description && <p className="project-description">{project.description}</p>}</section><aside className="panel project-summary"><p className="overline">Inventory summary</p><strong>{project.unit_count}</strong><span>Total units</span><div><p><b>{project.available_unit_count}</b> Available</p><p><b>{project.tower_count}</b> Towers</p></div><Link href={`/inventory?project_id=${project.id}`}>Search this inventory →</Link></aside></div>}
    {tab === "hierarchy" && <div className="hierarchy-grid"><section className="panel"><div className="panel-heading"><div><h2>Towers / blocks</h2><p>Project-level structural grouping.</p></div>{canCreateHierarchy && <button className="button button-secondary" onClick={() => openTower()}>Add tower</button>}</div><div className="hierarchy-list">{towers.map((item) => <article key={item.id}><span><strong>{item.name}</strong><small>{item.code} · {item.floor_count} floors · {item.unit_count} units</small></span>{canUpdateProject && <button onClick={() => openTower(item)}>Edit</button>}{canDeleteProject && <button className="danger-link" onClick={() => void deleteHierarchy("towers", item.id)}>Delete</button>}</article>)}{!towers.length && <p className="muted-copy">No towers configured.</p>}</div></section><section className="panel"><div className="panel-heading"><div><h2>Floors</h2><p>Floors remain scoped to their tower.</p></div>{canCreateHierarchy && towers.length > 0 && <button className="button button-secondary" onClick={() => openFloor()}>Add floor</button>}</div><div className="hierarchy-list">{floors.map((item) => <article key={item.id}><span><strong>{item.tower_name} · {item.name}</strong><small>Floor {item.floor_number} · {item.unit_count} units</small></span>{canUpdateProject && <button onClick={() => openFloor(item)}>Edit</button>}{canDeleteProject && <button className="danger-link" onClick={() => void deleteHierarchy("floors", item.id)}>Delete</button>}</article>)}{!floors.length && <p className="muted-copy">No floors configured.</p>}</div></section></div>}
    {tab === "units" && <section className="panel unit-management"><div className="panel-heading"><div><h2>Units</h2><p>Area, facing, configuration, pricing, amenities, and live status.</p></div>{canCreateUnit && <button className="button button-primary" onClick={() => openUnit()}>Add unit</button>}</div><div className="unit-admin-table"><div className="unit-admin-row head"><span>Unit</span><span>Hierarchy</span><span>Configuration</span><span>Price</span><span>Status</span><span /></div>{units.map((item) => <div className="unit-admin-row" key={item.id}><span><strong>{item.unit_number}</strong><small>{item.unit_type ?? "Unspecified"}</small></span><span>{item.tower_name ?? "—"}<small>{item.floor_name ?? "No floor"}</small></span><span>{item.area_sqft ? `${item.area_sqft} sq ft` : "Area not set"}<small>{item.facing ?? "Facing not set"} · {item.bedrooms ?? "—"} bed</small></span><span>{item.base_price ? new Intl.NumberFormat("en-IN", { style: "currency", currency: item.currency ?? "INR", maximumFractionDigits: 0 }).format(Number(item.base_price)) : "Not priced"}</span><span><em className={`inventory-status status-${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</em></span><span className="row-actions">{canUpdateUnit && <button onClick={() => openUnit(item)}>Edit</button>}{canDeleteUnit && <button className="danger-link" onClick={() => void deleteUnit(item.id)}>Delete</button>}</span></div>)}</div>{!units.length && <div className="customer-empty"><span>+</span><strong>No units configured</strong><p>Add real sellable inventory when it is ready.</p></div>}</section>}
    {editingProject && <div className="modal-backdrop"><form className="modal-card project-modal" onSubmit={saveProject}><div className="modal-heading"><div><p className="overline">Project</p><h2>Edit configuration</h2></div><button type="button" className="icon-button" onClick={() => setEditingProject(false)}>×</button></div><div className="customer-edit-scroll"><div className="lead-form-grid">{([ ["name", "Name"], ["project_type", "Project type"], ["rera_number", "RERA number"], ["default_currency", "Currency"], ["launch_date", "Launch date"], ["expected_possession_date", "Expected possession"], ["address_line1", "Address line 1"], ["address_line2", "Address line 2"], ["city", "City"], ["state", "State"], ["postal_code", "Postal code"], ["country", "Country"] ] as const).map(([field, label]) => <label className={`field ${["name", "address_line1", "address_line2"].includes(field) ? "span-two" : ""}`} key={field}><span>{label}</span><input type={field.includes("date") ? "date" : "text"} required={field === "name" || field === "default_currency"} value={projectDraft[field] ?? ""} onChange={(e) => setProjectDraft({ ...projectDraft, [field]: e.target.value })} /></label>)}<label className="field span-two"><span>Status</span><select value={projectDraft.status} onChange={(e) => setProjectDraft({ ...projectDraft, status: e.target.value })}>{statuses.map((item) => <option value={item} key={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label className="field span-two"><span>Amenities</span><input value={projectDraft.amenities} onChange={(e) => setProjectDraft({ ...projectDraft, amenities: e.target.value })} /></label><label className="field span-two"><span>Description</span><textarea value={projectDraft.description} onChange={(e) => setProjectDraft({ ...projectDraft, description: e.target.value })} /></label><label className="field span-two"><span>Advanced configuration (JSON)</span><textarea rows={5} value={projectDraft.configuration} onChange={(e) => setProjectDraft({ ...projectDraft, configuration: e.target.value })} /></label></div></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setEditingProject(false)}>Cancel</button><button className="button button-primary" disabled={saving}>Save changes</button></div></form></div>}
    {hierarchyDraft && <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={saveHierarchy}><div className="modal-heading"><h2>{hierarchyDraft.id ? "Edit" : "Add"} {hierarchyDraft.kind}</h2><button type="button" className="icon-button" onClick={() => setHierarchyDraft(null)}>×</button></div><div className="customer-edit-scroll form-stack">{hierarchyDraft.kind === "floor" && !hierarchyDraft.id && <label className="field"><span>Tower</span><select required value={hierarchyDraft.tower_id} onChange={(e) => setHierarchyDraft({ ...hierarchyDraft, tower_id: e.target.value })}>{towers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}<label className="field"><span>Name</span><input required value={hierarchyDraft.name} onChange={(e) => setHierarchyDraft({ ...hierarchyDraft, name: e.target.value })} /></label>{hierarchyDraft.kind === "tower" ? <label className="field"><span>Code</span><input required value={hierarchyDraft.code} onChange={(e) => setHierarchyDraft({ ...hierarchyDraft, code: e.target.value.toUpperCase() })} /></label> : <label className="field"><span>Floor number</span><input type="number" min="-20" max="300" required value={hierarchyDraft.floor_number} onChange={(e) => setHierarchyDraft({ ...hierarchyDraft, floor_number: e.target.value })} /></label>}<label className="toggle-field"><input type="checkbox" checked={hierarchyDraft.is_active} onChange={(e) => setHierarchyDraft({ ...hierarchyDraft, is_active: e.target.checked })} /><span><strong>Active</strong></span></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setHierarchyDraft(null)}>Cancel</button><button className="button button-primary" disabled={saving}>Save</button></div></form></div>}
    {unitDraft && <div className="modal-backdrop"><form className="modal-card unit-modal" onSubmit={saveUnit}><div className="modal-heading"><div><p className="overline">Inventory</p><h2>{unitDraft.id ? "Edit unit" : "Add unit"}</h2></div><button type="button" className="icon-button" onClick={() => setUnitDraft(null)}>×</button></div><div className="customer-edit-scroll"><div className="lead-form-grid"><label className="field"><span>Tower</span><select value={unitDraft.tower_id} onChange={(e) => setUnitDraft({ ...unitDraft, tower_id: e.target.value, floor_id: "" })}><option value="">No tower</option>{towers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Floor</span><select value={unitDraft.floor_id} disabled={!unitDraft.tower_id} onChange={(e) => setUnitDraft({ ...unitDraft, floor_id: e.target.value })}><option value="">No floor</option>{floors.filter((item) => item.tower_id === unitDraft.tower_id).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{([ ["unit_number", "Unit number"], ["unit_type", "Unit type"], ["area_sqft", "Saleable area (sq ft)"], ["carpet_area_sqft", "Carpet area (sq ft)"], ["built_up_area_sqft", "Built-up area (sq ft)"], ["facing", "Facing"], ["bedrooms", "Bedrooms"], ["bathrooms", "Bathrooms"], ["balconies", "Balconies"], ["base_price", "Base price"], ["currency", "Currency"] ] as const).map(([field, label]) => <label className="field" key={field}><span>{label}</span><input type={["area_sqft", "carpet_area_sqft", "built_up_area_sqft", "bedrooms", "bathrooms", "balconies", "base_price"].includes(field) ? "number" : "text"} required={field === "unit_number"} min="0" step="0.01" value={unitDraft[field]} onChange={(e) => setUnitDraft({ ...unitDraft, [field]: e.target.value })} /></label>)}<label className="field span-two"><span>Amenities</span><input value={unitDraft.amenities} onChange={(e) => setUnitDraft({ ...unitDraft, amenities: e.target.value })} placeholder="Parking, Balcony, Garden view" /></label><label className="field"><span>Price components (JSON)</span><textarea rows={5} value={unitDraft.price_components} onChange={(e) => setUnitDraft({ ...unitDraft, price_components: e.target.value })} /></label><label className="field"><span>Unit configuration (JSON)</span><textarea rows={5} value={unitDraft.configuration} onChange={(e) => setUnitDraft({ ...unitDraft, configuration: e.target.value })} /></label></div></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setUnitDraft(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? "Saving..." : "Save unit"}</button></div></form></div>}
  </main></AppShell>;
}
