"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { apiDownload, apiRequest, ApiError, CostSheet, PageResponse, permissionGranted, Quotation, QuotationStatus } from "@/lib/api";

const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Quotation is unavailable";
const money = (amount: string | null, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(amount ?? 0));

export default function QuotationDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { session } = useAuth(); const permissions = useMemo(() => session?.user.permissions ?? [], [session]);
  const [quote, setQuote] = useState<Quotation | null>(null); const [revisionSheets, setRevisionSheets] = useState<CostSheet[]>([]); const [sheetId, setSheetId] = useState(""); const [validUntil, setValidUntil] = useState(""); const [showVersion, setShowVersion] = useState(false); const [refresh, setRefresh] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const canUpdate = permissionGranted(permissions, "quotations.update"); const canExport = permissionGranted(permissions, "quotations.export");
  useEffect(() => { if (!session || !id) return; let active = true; void apiRequest<Quotation>(`/quotations/${id}`).then((data) => { if (active) setQuote(data); }).catch((reason: unknown) => { if (active) setError(message(reason)); }); return () => { active = false; }; }, [id, refresh, session]);
  useEffect(() => { if (!session || !quote?.customer_id || !canUpdate) return; let active = true; void apiRequest<PageResponse<CostSheet>>(`/cost-sheets?customer_id=${quote.customer_id}&status=APPROVED&page_size=100`).then((data) => { if (active) setRevisionSheets(data.items.filter((item) => item.unit_id === quote.unit_id)); }).catch(() => undefined); return () => { active = false; }; }, [canUpdate, quote?.customer_id, quote?.unit_id, session]);
  async function status(next: QuotationStatus) { setSaving(true); setError(null); try { await apiRequest(`/quotations/${id}/status`, { method: "POST", body: JSON.stringify({ status: next }) }); setNotice(`Quotation marked ${next.toLowerCase()}`); setRefresh((value) => value + 1); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function download() { setSaving(true); setError(null); try { const blob = await apiDownload(`/quotations/${id}/pdf`); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${quote?.quotation_number ?? "quotation"}-v${quote?.version ?? 1}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function createVersion(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const revision = await apiRequest<Quotation>(`/quotations/${id}/versions`, { method: "POST", body: JSON.stringify({ cost_sheet_id: sheetId, valid_until: validUntil }) }); router.push(`/quotations/${revision.id}`); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  if (!quote) return <AppShell><main className="dashboard-content"><div className="center-inline"><span className="spinner"/>Loading quotation...</div>{error && <div className="alert alert-error">{error}</div>}</main></AppShell>;
  return <AppShell><main className="dashboard-content quote-content"><Link className="back-link" href="/quotations">← Quotations</Link><div className="quote-detail-head"><div><p className="overline">{quote.project_name} · Unit {quote.unit_number ?? "—"}</p><h1>{quote.quotation_number} <small>v{quote.version}</small></h1><p>Prepared for <Link href={`/customers/${quote.customer_id}`}>{quote.customer_name}</Link> · Valid until {new Date(quote.valid_until).toLocaleDateString("en-IN")}</p></div><div className="heading-actions"><span className={`quote-status status-${quote.status.toLowerCase()}`}>{quote.status}</span>{canExport && <button disabled={saving} className="button button-secondary" onClick={() => void download()}>Download PDF</button>}{canUpdate && !["ACCEPTED", "REJECTED", "SUPERSEDED"].includes(quote.status) && <button className="button button-secondary" onClick={() => setShowVersion(true)}>New version</button>}</div></div>{error && <div className="alert alert-error page-alert">{error}</div>}{notice && <div className="alert alert-success page-alert">{notice}</div>}
    {canUpdate && <section className="quote-action-bar"><div><strong>Quotation lifecycle</strong><span>Each transition is backend-enforced and audit logged.</span></div><div>{quote.status === "DRAFT" && <button disabled={saving} className="primary" onClick={() => void status("SENT")}>Mark as sent</button>}{quote.status === "DRAFT" && <button disabled={saving} onClick={() => void status("EXPIRED")}>Expire</button>}{quote.status === "SENT" && <button disabled={saving} className="primary" onClick={() => void status("ACCEPTED")}>Accept</button>}{quote.status === "SENT" && <button disabled={saving} className="danger" onClick={() => void status("REJECTED")}>Reject</button>}{quote.status === "SENT" && <button disabled={saving} onClick={() => void status("EXPIRED")}>Expire</button>}</div></section>}
    <div className="quote-detail-grid"><div className="quote-main-stack"><section className="panel quotation-paper"><header><div><span>QUOTATION</span><strong>{quote.quotation_number}</strong></div><div><span>VERSION</span><strong>{quote.version}</strong></div></header><div className="quote-party"><div><small>PREPARED FOR</small><strong>{quote.customer_name ?? quote.lead_name}</strong></div><div><small>PROPERTY</small><strong>{quote.project_name} · {quote.unit_number}</strong></div></div><div className="detail-line-table"><div className="detail-line head"><span>Description</span><span>Quantity × rate</span><span>Amount</span></div>{quote.items.map((item) => <div className="detail-line" key={item.id}><span><strong>{item.description}</strong><small>{item.category?.replaceAll("_", " ")}</small></span><span>{item.quantity} × {money(item.unit_price, quote.currency)}</span><span>{money(item.total, quote.currency)}</span></div>)}</div><dl className="paper-totals"><div><dt>Subtotal</dt><dd>{money(quote.subtotal, quote.currency)}</dd></div><div><dt>Discount</dt><dd>− {money(quote.discount_amount, quote.currency)}</dd></div><div><dt>Taxes</dt><dd>{money(quote.tax_amount, quote.currency)}</dd></div><div><dt>Final agreed value</dt><dd>{money(quote.final_agreed_value ?? quote.total, quote.currency)}</dd></div><div><dt>Booking amount</dt><dd>{money(quote.booking_amount, quote.currency)}</dd></div></dl></section></div>
      <aside className="quote-side-stack"><section className="panel"><p className="overline">Version history</p><div className="version-list">{quote.history.map((version) => <Link className={version.id === quote.id ? "current" : ""} href={`/quotations/${version.id}`} key={version.id}><span><strong>Version {version.version}</strong><small>{new Date(version.created_at).toLocaleString("en-IN")}</small></span><span><em className={`quote-status status-${version.status.toLowerCase()}`}>{version.status}</em><b>{money(version.total, quote.currency)}</b></span></Link>)}</div></section><section className="panel"><p className="overline">Document facts</p><dl className="customer-side-facts"><div><dt>Prepared by</dt><dd>{quote.created_by_name}</dd></div><div><dt>Issued</dt><dd>{quote.issued_at ? new Date(quote.issued_at).toLocaleString("en-IN") : "Not sent"}</dd></div><div><dt>Valid until</dt><dd>{new Date(quote.valid_until).toLocaleDateString("en-IN")}</dd></div><div><dt>Cost sheet</dt><dd>{quote.cost_sheet_id ? <Link href={`/cost-sheets/${quote.cost_sheet_id}`}>Open source</Link> : "Legacy record"}</dd></div></dl></section></aside>
    </div>
    {showVersion && <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={createVersion}><div className="modal-heading"><div><h2>Create quotation version</h2><p>Only an approved cost sheet for the same customer and unit can be used.</p></div><button type="button" className="icon-button" onClick={() => setShowVersion(false)}>×</button></div><div className="form-stack"><label className="field"><span>Approved cost sheet</span><select required value={sheetId} onChange={(e) => setSheetId(e.target.value)}><option value="">Select revised cost sheet</option>{revisionSheets.map((sheet) => <option value={sheet.id ?? ""} key={sheet.id}>{new Date(sheet.created_at ?? "").toLocaleDateString("en-IN")} · {money(sheet.final_agreed_value, sheet.currency)}</option>)}</select></label><label className="field"><span>Valid until</span><input required min={new Date().toISOString().slice(0, 10)} type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)}/></label>{!revisionSheets.length && <p className="muted-copy">Create and approve a new cost sheet for this unit before revising.</p>}</div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setShowVersion(false)}>Cancel</button><button disabled={saving || !revisionSheets.length} className="button button-primary">Create version</button></div></form></div>}
  </main></AppShell>;
}
