"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import {
  apiRequest,
  ApiError,
  InAppNotification,
  NotificationMarkAllResult,
  PageResponse,
  permissionGranted
} from "@/lib/api";

function eventLabel(value: string) {
  return value.split("_").map((part) => `${part[0]}${part.slice(1).toLowerCase()}`).join(" ");
}

export default function NotificationsPage() {
  const router = useRouter();
  const { session } = useAuth();
  const canUpdate = permissionGranted(session?.user.permissions ?? [], "notifications.update");
  const [rows, setRows] = useState<PageResponse<InAppNotification> | null>(null);
  const [queryDraft, setQueryDraft] = useState("");
  const [query, setQuery] = useState("");
  const [unreadOnly, setUnreadOnly] = useState(false);
  const [page, setPage] = useState(1);
  const [refreshKey, setRefreshKey] = useState(0);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const params = new URLSearchParams({ page: String(page), page_size: "20" });
    if (query) params.set("q", query);
    if (unreadOnly) params.set("unread_only", "true");
    const data = await apiRequest<PageResponse<InAppNotification>>(`/notifications?${params}`);
    setRows(data);
    setError(null);
  }, [page, query, unreadOnly]);

  useEffect(() => {
    if (!session) return;
    let active = true;
    const timer = window.setTimeout(() => void load().catch((reason: unknown) => { if (active) setError(reason instanceof ApiError ? reason.message : "Notifications could not be loaded"); }), 0);
    return () => { active = false; window.clearTimeout(timer); };
  }, [load, refreshKey, session]);

  function search(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setPage(1);
    setQuery(queryDraft.trim());
  }

  async function openNotification(item: InAppNotification) {
    if (!item.read_at && canUpdate) await apiRequest(`/notifications/${item.id}/read`, { method: "PATCH" });
    router.push(item.action_url ?? "/notifications");
  }

  async function markAll() {
    if (!canUpdate) return;
    await apiRequest<NotificationMarkAllResult>("/notifications/read-all", { method: "POST" });
    setRefreshKey((value) => value + 1);
  }

  return <AppShell><main className="dashboard-content notification-page">
    <div className="management-heading"><div><p className="overline">Activity center</p><h1>Notifications</h1><p>Assignment, approval, financial, inventory and customer-service alerts generated by real CRM activity.</p></div>{canUpdate && rows?.items.some((item) => !item.read_at) && <button className="button button-secondary" type="button" onClick={() => void markAll()}>Mark all read</button>}</div>
    {error && <div className="alert alert-error page-alert" role="alert">{error}</div>}
    <div className="management-toolbar notification-toolbar"><form className="search-box" onSubmit={search}><span aria-hidden="true">⌕</span><input aria-label="Search notifications" value={queryDraft} onChange={(event) => setQueryDraft(event.target.value)} placeholder="Search notifications"/><button className="button button-primary" type="submit">Search</button></form><label className="notification-unread-filter"><input type="checkbox" checked={unreadOnly} onChange={(event) => { setUnreadOnly(event.target.checked); setPage(1); }}/><span>Unread only</span></label><span className="result-count" aria-live="polite">{rows?.total ?? 0} notifications</span></div>
    <section className="data-card notification-list">
      {rows?.items.map((item) => <button type="button" key={item.id} className={item.read_at ? "" : "unread"} onClick={() => void openNotification(item)}><i/><div><span className="notification-type">{eventLabel(item.event_type)}</span><h2>{item.title}</h2><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()} · {item.related_entity_type?.replaceAll("_", " ") ?? "System event"}</small></div><span className="notification-state">{item.read_at ? "Read" : "New"}</span></button>)}
      {rows && !rows.items.length && <div className="empty-state table-empty"><h3>{unreadOnly ? "No unread notifications" : "No notifications yet"}</h3><p>Only real events from your workspace create notifications.</p></div>}
      {!rows && !error && <div className="center-inline" aria-busy="true"><span className="spinner"/><span>Loading notifications…</span></div>}
      {rows && rows.pages > 1 && <div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><strong>{page} / {rows.pages}</strong><button type="button" disabled={page >= rows.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div>}
    </section>
  </main></AppShell>;
}
